const TEAMS = [
  {id:109,abbr:'ARI',city:'Arizona',    name:'Arizona Diamondbacks',  color:'#A71930',alt:'#E3D4AD'},
  {id:133,abbr:'ATH',city:'Oakland',    name:'Athletics',             color:'#003831',alt:'#EFB21E'},
  {id:144,abbr:'ATL',city:'Atlanta',    name:'Atlanta Braves',        color:'#CE1141',alt:'#13274F'},
  {id:110,abbr:'BAL',city:'Baltimore',  name:'Baltimore Orioles',     color:'#DF4601',alt:'#000000'},
  {id:111,abbr:'BOS',city:'Boston',     name:'Boston Red Sox',        color:'#BD3039',alt:'#0D2B56'},
  {id:112,abbr:'CHC',city:'Chicago',    name:'Chicago Cubs',          color:'#0E3386',alt:'#CC3433'},
  {id:145,abbr:'CWS',city:'Chicago',    name:'Chicago White Sox',     color:'#27251F',alt:'#C4CED4'},
  {id:113,abbr:'CIN',city:'Cincinnati', name:'Cincinnati Reds',       color:'#C6011F',alt:'#000000'},
  {id:114,abbr:'CLE',city:'Cleveland',  name:'Cleveland Guardians',   color:'#00385D',alt:'#E31937'},
  {id:115,abbr:'COL',city:'Colorado',   name:'Colorado Rockies',      color:'#33006F',alt:'#C4CED4'},
  {id:116,abbr:'DET',city:'Detroit',    name:'Detroit Tigers',        color:'#0C2340',alt:'#FA4616'},
  {id:117,abbr:'HOU',city:'Houston',    name:'Houston Astros',        color:'#002D62',alt:'#EB6E1F'},
  {id:118,abbr:'KC', city:'Kansas City',name:'Kansas City Royals',    color:'#004687',alt:'#C09A5B'},
  {id:108,abbr:'LAA',city:'Los Angeles',name:'Los Angeles Angels',    color:'#BA0021',alt:'#003263'},
  {id:119,abbr:'LAD',city:'Los Angeles',name:'Los Angeles Dodgers',   color:'#005A9C',alt:'#EF3E42'},
  {id:146,abbr:'MIA',city:'Miami',      name:'Miami Marlins',         color:'#00A3E0',alt:'#EF3340'},
  {id:158,abbr:'MIL',city:'Milwaukee',  name:'Milwaukee Brewers',     color:'#12284B',alt:'#FFC52F'},
  {id:142,abbr:'MIN',city:'Minnesota',  name:'Minnesota Twins',       color:'#002B5C',alt:'#D31145'},
  {id:121,abbr:'NYM',city:'New York',   name:'New York Mets',         color:'#002D72',alt:'#FF5910'},
  {id:147,abbr:'NYY',city:'New York',   name:'New York Yankees',      color:'#132448',alt:'#C4CED4'},
  {id:143,abbr:'PHI',city:'Philadelphia',name:'Philadelphia Phillies',color:'#E81828',alt:'#002D72'},
  {id:134,abbr:'PIT',city:'Pittsburgh', name:'Pittsburgh Pirates',    color:'#27251F',alt:'#FDB827'},
  {id:135,abbr:'SD', city:'San Diego',  name:'San Diego Padres',      color:'#2F241D',alt:'#FFC425'},
  {id:137,abbr:'SF', city:'San Francisco',name:'San Francisco Giants',color:'#FD5A1E',alt:'#27251F'},
  {id:136,abbr:'SEA',city:'Seattle',    name:'Seattle Mariners',      color:'#0C2C56',alt:'#005C5C'},
  {id:138,abbr:'STL',city:'St. Louis',  name:'St. Louis Cardinals',   color:'#C41E3A',alt:'#FEDB00'},
  {id:139,abbr:'TB', city:'Tampa Bay',  name:'Tampa Bay Rays',        color:'#092C5C',alt:'#8FBCE6'},
  {id:140,abbr:'TEX',city:'Texas',      name:'Texas Rangers',         color:'#003278',alt:'#C0111F'},
  {id:141,abbr:'TOR',city:'Toronto',    name:'Toronto Blue Jays',     color:'#134A8E',alt:'#E8291C'},
  {id:120,abbr:'WSH',city:'Washington', name:'Washington Nationals',  color:'#AB0003',alt:'#14225A'},
];

const HITTING_STATS = [
  // ── Counting stats ────────────────────────────────────────────────────────
  {key:'homeRuns',            label:'Home Runs',               type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'rbi',                 label:'RBI',                     type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'hits',                label:'Hits',                    type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'runs',                label:'Runs Scored',             type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'stolenBases',         label:'Stolen Bases',            type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'strikeOuts',          label:'Strikeouts (Batter)',     type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'baseOnBalls',         label:'Walks',                   type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'doubles',             label:'Doubles',                 type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'triples',             label:'Triples',                 type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'totalBases',          label:'Total Bases',             type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'plateAppearances',    label:'Plate Appearances',       type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'atBats',              label:'At Bats',                 type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'gamesPlayed',         label:'Games Played',            type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'sacFlies',            label:'Sacrifice Flies',         type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'sacBunts',            label:'Sacrifice Bunts',         type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'hitByPitch',          label:'Hit By Pitch',            type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'intentionalWalks',    label:'Intentional Walks',       type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'caughtStealing',      label:'Caught Stealing',         type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'groundIntoDoublePlay',label:'Ground Into DP',          type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'leftOnBase',          label:'Left On Base',            type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'numberOfPitches',     label:'Pitches Seen',            type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'groundOuts',          label:'Ground Outs',             type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  // ── Rate / ratio stats ────────────────────────────────────────────────────
  {key:'avg',                 label:'Batting Average',         type:'season',      careerOk:true,  fmt:v=>parseFloat(v).toFixed(3),         order:'desc', pool:'Qualified'},
  {key:'ops',                 label:'OPS',                     type:'season',      careerOk:true,  fmt:v=>parseFloat(v).toFixed(3),         order:'desc', pool:'Qualified'},
  {key:'slg',                 label:'Slugging %',              type:'season',      careerOk:true,  fmt:v=>parseFloat(v).toFixed(3),         order:'desc', pool:'Qualified'},
  {key:'obp',                 label:'On-Base %',               type:'season',      careerOk:true,  fmt:v=>parseFloat(v).toFixed(3),         order:'desc', pool:'Qualified'},
  {key:'babip',               label:'BABIP',                   type:'season',      careerOk:true,  fmt:v=>parseFloat(v).toFixed(3),         order:'desc', pool:'Qualified'},
  {key:'stolenBasePercentage',label:'Stolen Base %',           type:'season',      careerOk:true,  fmt:v=>parseFloat(v).toFixed(3),         order:'desc', pool:'Qualified'},
  {key:'atBatsPerHomeRun',    label:'AB Per Home Run',         type:'season',      careerOk:true,  fmt:v=>parseFloat(v).toFixed(1),         order:'asc',  pool:'Qualified'},
  {key:'groundOutsToAirouts', label:'GB/FB Ratio',             type:'season',      careerOk:false, fmt:v=>parseFloat(v).toFixed(2),         order:'desc', pool:'Qualified'},
  // ── Advanced (season) ─────────────────────────────────────────────────────
  {key:'war',                 label:'WAR',                     type:'sabermetrics',careerOk:false, fmt:v=>parseFloat(v).toFixed(1),         order:'desc'},
  {key:'woba',                label:'wOBA',                    type:'sabermetrics',careerOk:false, fmt:v=>parseFloat(v).toFixed(3),         order:'desc', pool:'Qualified'},
  {key:'wRcPlus',             label:'wRC+',                    type:'sabermetrics',careerOk:false, fmt:v=>Math.round(v)+'',                 order:'desc', pool:'Qualified'},
  // ── All-Time only (careerAdvanced) ────────────────────────────────────────
  {key:'extraBaseHits',               label:'Extra Base Hits',          type:'careerAdvanced',careerOk:true,  fmt:v=>+v,                           order:'desc'},
  {key:'flyOuts',                     label:'Fly Outs',                 type:'careerAdvanced',careerOk:true,  fmt:v=>+v,                           order:'desc'},
  {key:'reachedOnError',              label:'Reached On Error',         type:'careerAdvanced',careerOk:true,  fmt:v=>+v,                           order:'desc'},
  {key:'walkOffs',                    label:'Walk-Off Hits',            type:'careerAdvanced',careerOk:true,  fmt:v=>+v,                           order:'desc'},
  {key:'iso',                         label:'ISO (Isolated Power)',     type:'careerAdvanced',careerOk:true,  fmt:v=>parseFloat(v).toFixed(3),     order:'desc', pool:'Qualified'},
  {key:'walksPerPlateAppearance',     label:'BB/PA',                    type:'careerAdvanced',careerOk:true,  fmt:v=>parseFloat(v).toFixed(3),     order:'desc', pool:'Qualified'},
  {key:'strikeoutsPerPlateAppearance',label:'K/PA',                     type:'careerAdvanced',careerOk:true,  fmt:v=>parseFloat(v).toFixed(3),     order:'desc', pool:'Qualified'},
  {key:'homeRunsPerPlateAppearance',  label:'HR/PA',                    type:'careerAdvanced',careerOk:true,  fmt:v=>parseFloat(v).toFixed(4),     order:'desc', pool:'Qualified'},
  {key:'walksPerStrikeout',           label:'BB/K Ratio',               type:'careerAdvanced',careerOk:true,  fmt:v=>parseFloat(v).toFixed(3),     order:'desc', pool:'Qualified'},
  {key:'pitchesPerPlateAppearance',   label:'Pitches Per PA',           type:'careerAdvanced',careerOk:true,  fmt:v=>parseFloat(v).toFixed(2),     order:'desc', pool:'Qualified'},
];
const PITCHING_STATS = [
  // ── Counting stats ────────────────────────────────────────────────────────
  {key:'strikeOuts',          label:'Strikeouts',              type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'wins',                label:'Wins',                    type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'saves',               label:'Saves',                   type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'saveOpportunities',   label:'Save Opportunities',      type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'holds',               label:'Holds',                   type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'homeRuns',            label:'Home Runs Allowed',       type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'baseOnBalls',         label:'Walks Allowed',           type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'hits',                label:'Hits Allowed',            type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'gamesStarted',        label:'Games Started',           type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'gamesPitched',        label:'Games Pitched',           type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'gamesFinished',       label:'Games Finished',          type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'losses',              label:'Losses',                  type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'battersFaced',        label:'Batters Faced',           type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'blownSaves',          label:'Blown Saves',             type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'completeGames',       label:'Complete Games',          type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'shutouts',            label:'Shutouts',                type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'wildPitches',         label:'Wild Pitches',            type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'hitBatsmen',          label:'Hit Batters (HBP)',       type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'balks',               label:'Balks',                   type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'pickoffs',            label:'Pickoffs',                type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'inheritedRunners',    label:'Inherited Runners',       type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'inheritedRunnersScored',label:'Inherited Runs Scored', type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'earnedRuns',          label:'Earned Runs Allowed',     type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'outs',                label:'Outs Recorded',           type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  {key:'strikes',             label:'Strikes Thrown',          type:'season',      careerOk:true,  fmt:v=>+v,                               order:'desc'},
  // ── Rate stats ───────────────────────────────────────────────────────────
  {key:'era',                 label:'ERA',                     type:'season',      careerOk:true,  fmt:v=>parseFloat(v).toFixed(2),         order:'asc',  pool:'Qualified'},
  {key:'whip',                label:'WHIP',                    type:'season',      careerOk:true,  fmt:v=>parseFloat(v).toFixed(2),         order:'asc',  pool:'Qualified'},
  {key:'strikeoutsPer9Inn',   label:'K/9',                     type:'season',      careerOk:false, fmt:v=>parseFloat(v).toFixed(1),         order:'desc', pool:'Qualified'},
  {key:'walksPer9Inn',        label:'BB/9',                    type:'season',      careerOk:false, fmt:v=>parseFloat(v).toFixed(1),         order:'asc',  pool:'Qualified'},
  {key:'hitsPer9Inn',         label:'H/9',                     type:'season',      careerOk:false, fmt:v=>parseFloat(v).toFixed(1),         order:'asc',  pool:'Qualified'},
  {key:'strikeoutWalkRatio',  label:'K/BB Ratio',              type:'season',      careerOk:false, fmt:v=>parseFloat(v).toFixed(2),         order:'desc', pool:'Qualified'},
  {key:'pitchesPerInning',    label:'Pitches Per Inning',      type:'season',      careerOk:false, fmt:v=>parseFloat(v).toFixed(2),         order:'asc',  pool:'Qualified'},
  {key:'winPercentage',       label:'Win %',                   type:'season',      careerOk:true,  fmt:v=>parseFloat(v).toFixed(3),         order:'desc', pool:'Qualified'},
  // ── Advanced ─────────────────────────────────────────────────────────────
  {key:'war',                 label:'WAR',                     type:'sabermetrics',careerOk:false, fmt:v=>parseFloat(v).toFixed(1),         order:'desc'},
  {key:'fip',                 label:'FIP',                     type:'sabermetrics',careerOk:false, fmt:v=>parseFloat(v).toFixed(2),         order:'asc',  pool:'Qualified'},
  {key:'xfip',                label:'xFIP',                    type:'sabermetrics',careerOk:false, fmt:v=>parseFloat(v).toFixed(2),         order:'asc',  pool:'Qualified'},
  {key:'eraMinus',            label:'ERA-',                    type:'sabermetrics',careerOk:false, fmt:v=>Math.round(v)+'',                 order:'asc',  pool:'Qualified'},
  {key:'fipMinus',            label:'FIP-',                    type:'sabermetrics',careerOk:false, fmt:v=>Math.round(v)+'',                 order:'asc',  pool:'Qualified'},
  {key:'ra9War',              label:'RA9-WAR',                 type:'sabermetrics',careerOk:false, fmt:v=>parseFloat(v).toFixed(1),         order:'desc'},
  {key:'pli',                 label:'Leverage Index (pLI)',    type:'sabermetrics',careerOk:false, fmt:v=>parseFloat(v).toFixed(2),         order:'desc'},
];

function logoUrl(id){ return `https://www.mlbstatic.com/team-logos/${id}.svg`; }

function logoImg(teamId, color, alt, abbr, size=36){
  return `<img src="${logoUrl(teamId)}" width="${size}" height="${size}" style="object-fit:contain;flex-shrink:0"
    onerror="this.outerHTML='<div style=\\'width:${size}px;height:${size}px;border-radius:50%;background:${color};color:${alt};display:flex;align-items:center;justify-content:center;font-family:Barlow Condensed,sans-serif;font-size:${Math.max(7,size/3.2)|0}px;\\'>${abbr}</div>'" alt="${abbr}"/>`;
}

function norm(s){
  return s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[^a-z0-9\s]/g,'').trim();
}
function isMatch(guess, playerName){
  const g=norm(guess), full=norm(playerName);
  if(full===g) return true;
  const tokens=full.split(/\s+/), last=tokens[tokens.length-1];
  if(last.length>=4 && last===g) return true;
  const noSfx=tokens.filter(t=>!['jr','sr','ii','iii','iv'].includes(t));
  if(noSfx.join(' ')===g) return true;
  if(noSfx[noSfx.length-1]?.length>=4 && noSfx[noSfx.length-1]===g) return true;
  return false;
}


// ── Baseball Reference Static Datasets ───────────────────────────────────────
// Manually imported from Baseball Reference — includes historical players
// the MLB Stats API doesn't cover (e.g. Cap Anson, 19th century stats)

const BBREF_RBI_ALL_TIME = [
  {rank:1,name:'Henry Aaron',value:'2297',nameLower:'henry aaron'},
  {rank:2,name:'Albert Pujols',value:'2218',nameLower:'albert pujols'},
  {rank:3,name:'Babe Ruth',value:'2214',nameLower:'babe ruth'},
  {rank:4,name:'Alex Rodriguez',value:'2086',nameLower:'alex rodriguez'},
  {rank:5,name:'Cap Anson',value:'2075',nameLower:'cap anson'},
  {rank:6,name:'Barry Bonds',value:'1996',nameLower:'barry bonds'},
  {rank:7,name:'Lou Gehrig',value:'1995',nameLower:'lou gehrig'},
  {rank:8,name:'Stan Musial',value:'1951',nameLower:'stan musial'},
  {rank:9,name:'Ty Cobb',value:'1944',nameLower:'ty cobb'},
  {rank:10,name:'Jimmie Foxx',value:'1922',nameLower:'jimmie foxx'},
  {rank:11,name:'Eddie Murray',value:'1917',nameLower:'eddie murray'},
  {rank:12,name:'Willie Mays',value:'1909',nameLower:'willie mays'},
  {rank:13,name:'Miguel Cabrera',value:'1881',nameLower:'miguel cabrera'},
  {rank:14,name:'Mel Ott',value:'1860',nameLower:'mel ott'},
  {rank:15,name:'Carl Yastrzemski',value:'1844',nameLower:'carl yastrzemski'},
  {rank:16,name:'Ted Williams',value:'1839',nameLower:'ted williams'},
  {rank:17,name:'Ken Griffey Jr.',value:'1836',nameLower:'ken griffey jr.'},
  {rank:18,name:'Rafael Palmeiro',value:'1835',nameLower:'rafael palmeiro'},
  {rank:19,name:'Dave Winfield',value:'1833',nameLower:'dave winfield'},
  {rank:20,name:'Manny Ramirez',value:'1831',nameLower:'manny ramirez'},
  {rank:21,name:'Al Simmons',value:'1828',nameLower:'al simmons'},
  {rank:22,name:'Frank Robinson',value:'1812',nameLower:'frank robinson'},
  {rank:23,name:'David Ortiz',value:'1768',nameLower:'david ortiz'},
  {rank:24,name:'Honus Wagner',value:'1732',nameLower:'honus wagner'},
  {rank:25,name:'Adrian Beltré',value:'1707',nameLower:'adrian beltré'},
  {rank:26,name:'Frank Thomas',value:'1704',nameLower:'frank thomas'},
  {rank:27,name:'Reggie Jackson',value:'1702',nameLower:'reggie jackson'},
  {rank:28,name:'Jim Thome',value:'1699',nameLower:'jim thome'},
  {rank:29,name:'Cal Ripken Jr.',value:'1695',nameLower:'cal ripken jr.'},
  {rank:30,name:'Gary Sheffield',value:'1676',nameLower:'gary sheffield'},
  {rank:31,name:'Sammy Sosa',value:'1667',nameLower:'sammy sosa'},
  {rank:32,name:'Tony Pérez',value:'1652',nameLower:'tony pérez'},
  {rank:33,name:'Ernie Banks',value:'1636',nameLower:'ernie banks'},
  {rank:34,name:'Harold Baines',value:'1628',nameLower:'harold baines'},
  {rank:35,name:'Chipper Jones',value:'1623',nameLower:'chipper jones'},
  {rank:36,name:'Goose Goslin',value:'1612',nameLower:'goose goslin'},
  {rank:37,name:'Nap Lajoie',value:'1599',nameLower:'nap lajoie'},
  {rank:38,name:'George Brett',value:'1596',nameLower:'george brett'},
  {rank:39,name:'Mike Schmidt',value:'1595',nameLower:'mike schmidt'},
  {rank:40,name:'Andre Dawson',value:'1591',nameLower:'andre dawson'},
  {rank:41,name:'Carlos Beltrán',value:'1587',nameLower:'carlos beltrán'},
  {rank:42,name:'Rogers Hornsby',value:'1584',nameLower:'rogers hornsby'},
  {rank:42,name:'Harmon Killebrew',value:'1584',nameLower:'harmon killebrew'},
  {rank:43,name:'Al Kaline',value:'1582',nameLower:'al kaline'},
  {rank:44,name:'Jake Beckley',value:'1581',nameLower:'jake beckley'},
  {rank:45,name:'Willie McCovey',value:'1555',nameLower:'willie mccovey'},
  {rank:46,name:'Fred McGriff',value:'1550',nameLower:'fred mcgriff'},
  {rank:47,name:'Harry Heilmann',value:'1543',nameLower:'harry heilmann'},
  {rank:48,name:'Willie Stargell',value:'1540',nameLower:'willie stargell'},
  {rank:49,name:'Joe DiMaggio',value:'1537',nameLower:'joe dimaggio'},
  {rank:50,name:'Tris Speaker',value:'1531',nameLower:'tris speaker'},
  {rank:51,name:'Jeff Bagwell',value:'1529',nameLower:'jeff bagwell'},
  {rank:52,name:'Sam Crawford',value:'1523',nameLower:'sam crawford'},
  {rank:53,name:'Jeff Kent',value:'1518',nameLower:'jeff kent'},
  {rank:54,name:'Carlos Delgado',value:'1512',nameLower:'carlos delgado'},
  {rank:55,name:'Mickey Mantle',value:'1509',nameLower:'mickey mantle'},
  {rank:56,name:'Vladimir Guerrero',value:'1496',nameLower:'vladimir guerrero'},
  {rank:57,name:'Dave Parker',value:'1493',nameLower:'dave parker'},
  {rank:58,name:'Billy Williams',value:'1475',nameLower:'billy williams'},
  {rank:59,name:'Ed Delahanty',value:'1466',nameLower:'ed delahanty'},
  {rank:59,name:'Rusty Staub',value:'1466',nameLower:'rusty staub'},
  {rank:60,name:'Eddie Mathews',value:'1453',nameLower:'eddie mathews'},
  {rank:61,name:'Jim Rice',value:'1451',nameLower:'jim rice'},
  {rank:62,name:'Joe Carter',value:'1445',nameLower:'joe carter'},
  {rank:63,name:'Jason Giambi',value:'1441',nameLower:'jason giambi'},
  {rank:64,name:'George Davis',value:'1440',nameLower:'george davis'},
  {rank:65,name:'Luis Gonzalez',value:'1439',nameLower:'luis gonzalez'},
  {rank:66,name:'Yogi Berra',value:'1430',nameLower:'yogi berra'},
  {rank:67,name:'Charlie Gehringer',value:'1427',nameLower:'charlie gehringer'},
  {rank:68,name:'Andrés Galarraga',value:'1425',nameLower:'andrés galarraga'},
  {rank:69,name:'Joe Cronin',value:'1424',nameLower:'joe cronin'},
  {rank:70,name:'Jim Bottomley',value:'1422',nameLower:'jim bottomley'},
  {rank:71,name:'Aramis Ramírez',value:'1417',nameLower:'aramis ramírez'},
  {rank:72,name:'Mark McGwire',value:'1414',nameLower:'mark mcgwire'},
  {rank:73,name:'Paul Konerko',value:'1412',nameLower:'paul konerko'},
  {rank:74,name:'José Canseco',value:'1407',nameLower:'josé canseco'},
  {rank:75,name:'Todd Helton',value:'1406',nameLower:'todd helton'},
  {rank:75,name:'Robin Yount',value:'1406',nameLower:'robin yount'},
  {rank:76,name:'Juan González',value:'1404',nameLower:'juan gonzález'},
  {rank:77,name:'Torii Hunter',value:'1391',nameLower:'torii hunter'},
  {rank:78,name:'Ted Simmons',value:'1389',nameLower:'ted simmons'},
  {rank:79,name:'Dwight Evans',value:'1384',nameLower:'dwight evans'},
  {rank:80,name:'Joe Medwick',value:'1383',nameLower:'joe medwick'},
  {rank:81,name:'Lave Cross',value:'1378',nameLower:'lave cross'},
  {rank:82,name:'Johnny Bench',value:'1376',nameLower:'johnny bench'},
  {rank:83,name:'Chili Davis',value:'1372',nameLower:'chili davis'},
  {rank:84,name:'Freddie Freeman',value:'1371',nameLower:'freddie freeman'},
  {rank:85,name:'Garret Anderson',value:'1365',nameLower:'garret anderson'},
  {rank:85,name:'Orlando Cepeda',value:'1365',nameLower:'orlando cepeda'},
  {rank:86,name:'Bobby Abreu',value:'1363',nameLower:'bobby abreu'},
  {rank:86,name:'Carlos Lee',value:'1363',nameLower:'carlos lee'},
  {rank:87,name:'Brooks Robinson',value:'1357',nameLower:'brooks robinson'},
  {rank:88,name:'Darrell Evans',value:'1354',nameLower:'darrell evans'},
  {rank:89,name:'Gary Gaetti',value:'1341',nameLower:'gary gaetti'},
  {rank:90,name:'Johnny Mize',value:'1337',nameLower:'johnny mize'},
  {rank:91,name:'Mike Piazza',value:'1335',nameLower:'mike piazza'},
  {rank:92,name:'Duke Snider',value:'1333',nameLower:'duke snider'},
  {rank:93,name:'Iván Rodríguez',value:'1332',nameLower:'iván rodríguez'},
  {rank:94,name:'Ron Santo',value:'1331',nameLower:'ron santo'},
  {rank:95,name:'Carlton Fisk',value:'1330',nameLower:'carlton fisk'},
  {rank:96,name:'Al Oliver',value:'1326',nameLower:'al oliver'},
  {rank:97,name:'Nelson Cruz',value:'1325',nameLower:'nelson cruz'},
  {rank:98,name:'Roger Connor',value:'1323',nameLower:'roger connor'},
  {rank:99,name:'Rubén Sierra',value:'1322',nameLower:'rubén sierra'},
  {rank:100,name:'Graig Nettles',value:'1314',nameLower:'graig nettles'},
  {rank:100,name:'Pete Rose',value:'1314',nameLower:'pete rose'},
  {rank:101,name:'Derek Jeter',value:'1311',nameLower:'derek jeter'},
  {rank:101,name:'Mickey Vernon',value:'1311',nameLower:'mickey vernon'},
  {rank:101,name:'Larry Walker',value:'1311',nameLower:'larry walker'},
  {rank:102,name:'Paul Waner',value:'1309',nameLower:'paul waner'},
  {rank:103,name:'Steve Garvey',value:'1308',nameLower:'steve garvey'},
  {rank:103,name:'Sam Thompson',value:'1308',nameLower:'sam thompson'},
  {rank:104,name:'Paul Molitor',value:'1307',nameLower:'paul molitor'},
  {rank:105,name:'Robinson Canó',value:'1306',nameLower:'robinson canó'},
  {rank:106,name:'Roberto Clemente',value:'1305',nameLower:'roberto clemente'},
  {rank:107,name:'Enos Slaughter',value:'1304',nameLower:'enos slaughter'},
  {rank:108,name:'Hugh Duffy',value:'1302',nameLower:'hugh duffy'},
  {rank:108,name:'Miguel Tejada',value:'1302',nameLower:'miguel tejada'},
  {rank:109,name:'Dan Brouthers',value:'1301',nameLower:'dan brouthers'},
  {rank:110,name:'Eddie Collins',value:'1299',nameLower:'eddie collins'},
  {rank:111,name:'Mark Teixeira',value:'1298',nameLower:'mark teixeira'},
  {rank:112,name:'Andruw Jones',value:'1289',nameLower:'andruw jones'},
  {rank:113,name:'Moisés Alou',value:'1287',nameLower:'moisés alou'},
  {rank:113,name:'Scott Rolen',value:'1287',nameLower:'scott rolen'},
  {rank:114,name:'Del Ennis',value:'1284',nameLower:'del ennis'},
  {rank:115,name:'Bob Johnson',value:'1283',nameLower:'bob johnson'},
  {rank:116,name:'Don Baylor',value:'1276',nameLower:'don baylor'},
  {rank:117,name:'Hank Greenberg',value:'1274',nameLower:'hank greenberg'},
  {rank:117,name:'Gil Hodges',value:'1274',nameLower:'gil hodges'},
  {rank:118,name:'Paul Goldschmidt',value:'1273',nameLower:'paul goldschmidt'},
  {rank:118,name:'Pie Traynor',value:'1273',nameLower:'pie traynor'},
  {rank:119,name:'Tino Martinez',value:'1271',nameLower:'tino martinez'},
  {rank:120,name:'Paul O\'Neill',value:'1269',nameLower:'paul o\'neill'},
  {rank:121,name:'Dale Murphy',value:'1266',nameLower:'dale murphy'},
  {rank:122,name:'Edwin Encarnación',value:'1261',nameLower:'edwin encarnación'},
  {rank:122,name:'Edgar Martínez',value:'1261',nameLower:'edgar martínez'},
  {rank:123,name:'Bernie Williams',value:'1257',nameLower:'bernie williams'},
  {rank:124,name:'Zack Wheat',value:'1248',nameLower:'zack wheat'},
  {rank:125,name:'Bobby Doerr',value:'1247',nameLower:'bobby doerr'},
  {rank:126,name:'Frankie Frisch',value:'1244',nameLower:'frankie frisch'},
  {rank:126,name:'Lee May',value:'1244',nameLower:'lee may'},
  {rank:127,name:'Albert Belle',value:'1239',nameLower:'albert belle'},
  {rank:127,name:'George Foster',value:'1239',nameLower:'george foster'},
  {rank:128,name:'Magglio Ordóñez',value:'1236',nameLower:'magglio ordóñez'},
  {rank:129,name:'Lance Berkman',value:'1234',nameLower:'lance berkman'},
  {rank:129,name:'Bill Dahlen',value:'1234',nameLower:'bill dahlen'},
  {rank:130,name:'John Olerud',value:'1230',nameLower:'john olerud'},
  {rank:131,name:'Gary Carter',value:'1225',nameLower:'gary carter'},
  {rank:132,name:'Nolan Arenado',value:'1221',nameLower:'nolan arenado'},
  {rank:133,name:'Matt Holliday',value:'1220',nameLower:'matt holliday'},
  {rank:134,name:'Matt Williams',value:'1218',nameLower:'matt williams'},
  {rank:135,name:'Dave Kingman',value:'1210',nameLower:'dave kingman'},
  {rank:136,name:'Bill Dickey',value:'1209',nameLower:'bill dickey'},
  {rank:137,name:'Bill Buckner',value:'1208',nameLower:'bill buckner'},
  {rank:137,name:'Jim O\'Rourke',value:'1208',nameLower:'jim o\'rourke'},
  {rank:138,name:'Raúl Ibañez',value:'1207',nameLower:'raúl ibañez'},
  {rank:139,name:'Ellis Burks',value:'1206',nameLower:'ellis burks'},
  {rank:140,name:'Will Clark',value:'1205',nameLower:'will clark'},
  {rank:141,name:'Adrián González',value:'1202',nameLower:'adrián gonzález'},
  {rank:142,name:'Chuck Klein',value:'1201',nameLower:'chuck klein'},
  {rank:143,name:'Jim Edmonds',value:'1199',nameLower:'jim edmonds'},
  {rank:144,name:'Bob Elliott',value:'1195',nameLower:'bob elliott'},
  {rank:144,name:'Manny Machado',value:'1195',nameLower:'manny machado'},
  {rank:145,name:'Julio Franco',value:'1194',nameLower:'julio franco'},
  {rank:145,name:'Ryan Howard',value:'1194',nameLower:'ryan howard'},
  {rank:145,name:'Joe Kelley',value:'1194',nameLower:'joe kelley'},
  {rank:145,name:'Tony Lazzeri',value:'1194',nameLower:'tony lazzeri'},
  {rank:146,name:'Boog Powell',value:'1187',nameLower:'boog powell'},
  {rank:147,name:'Joe Torre',value:'1185',nameLower:'joe torre'},
  {rank:148,name:'Heinie Manush',value:'1183',nameLower:'heinie manush'},
  {rank:148,name:'Giancarlo Stanton',value:'1183',nameLower:'giancarlo stanton'},
  {rank:149,name:'Robin Ventura',value:'1182',nameLower:'robin ventura'},
  {rank:150,name:'Jack Clark',value:'1180',nameLower:'jack clark'},
  {rank:151,name:'Gabby Hartnett',value:'1179',nameLower:'gabby hartnett'},
  {rank:152,name:'Víctor Martínez',value:'1178',nameLower:'víctor martínez'},
  {rank:152,name:'George Sisler',value:'1178',nameLower:'george sisler'},
  {rank:152,name:'Vic Wertz',value:'1178',nameLower:'vic wertz'},
  {rank:153,name:'Sherry Magee',value:'1176',nameLower:'sherry magee'},
  {rank:154,name:'Craig Biggio',value:'1175',nameLower:'craig biggio'},
  {rank:155,name:'Vern Stephens',value:'1174',nameLower:'vern stephens'},
  {rank:155,name:'Bobby Veach',value:'1174',nameLower:'bobby veach'},
  {rank:156,name:'Bobby Bonilla',value:'1173',nameLower:'bobby bonilla'},
  {rank:157,name:'Vada Pinson',value:'1169',nameLower:'vada pinson'},
  {rank:158,name:'Adam Dunn',value:'1168',nameLower:'adam dunn'},
  {rank:159,name:'Steve Finley',value:'1167',nameLower:'steve finley'},
  {rank:160,name:'Earl Averill',value:'1164',nameLower:'earl averill'},
  {rank:161,name:'Willie Horton',value:'1163',nameLower:'willie horton'},
  {rank:162,name:'Rocky Colavito',value:'1159',nameLower:'rocky colavito'},
  {rank:162,name:'Evan Longoria',value:'1159',nameLower:'evan longoria'},
  {rank:162,name:'Alfonso Soriano',value:'1159',nameLower:'alfonso soriano'},
  {rank:163,name:'Andrew McCutchen',value:'1157',nameLower:'andrew mccutchen'},
  {rank:164,name:'Ryan Braun',value:'1154',nameLower:'ryan braun'},
  {rank:165,name:'B.J. Surhoff',value:'1153',nameLower:'b.j. surhoff'},
  {rank:166,name:'Rudy York',value:'1149',nameLower:'rudy york'},
  {rank:167,name:'Roy Sievers',value:'1147',nameLower:'roy sievers'},
  {rank:168,name:'Mark Grace',value:'1146',nameLower:'mark grace'},
  {rank:169,name:'Joey Votto',value:'1144',nameLower:'joey votto'},
  {rank:170,name:'Dante Bichette',value:'1141',nameLower:'dante bichette'},
  {rank:170,name:'Ken Boyer',value:'1141',nameLower:'ken boyer'},
  {rank:171,name:'Ron Cey',value:'1139',nameLower:'ron cey'},
  {rank:171,name:'Johnny Damon',value:'1139',nameLower:'johnny damon'},
  {rank:172,name:'Tony Gwynn',value:'1138',nameLower:'tony gwynn'},
  {rank:173,name:'Tommy Corcoran',value:'1137',nameLower:'tommy corcoran'},
  {rank:174,name:'Carlos Santana',value:'1136',nameLower:'carlos santana'},
  {rank:175,name:'Roberto Alomar',value:'1134',nameLower:'roberto alomar'},
  {rank:176,name:'Joe Morgan',value:'1133',nameLower:'joe morgan'},
  {rank:177,name:'Greg Luzinski',value:'1128',nameLower:'greg luzinski'},
  {rank:178,name:'Cecil Cooper',value:'1125',nameLower:'cecil cooper'},
  {rank:178,name:'Tim Wallach',value:'1125',nameLower:'tim wallach'},
  {rank:179,name:'Ed McKean',value:'1124',nameLower:'ed mckean'},
  {rank:180,name:'Joe Adcock',value:'1122',nameLower:'joe adcock'},
  {rank:181,name:'Bobby Wallace',value:'1121',nameLower:'bobby wallace'},
  {rank:182,name:'Dick Allen',value:'1119',nameLower:'dick allen'},
  {rank:182,name:'Frank Howard',value:'1119',nameLower:'frank howard'},
  {rank:183,name:'Luke Appling',value:'1116',nameLower:'luke appling'},
  {rank:184,name:'Rickey Henderson',value:'1115',nameLower:'rickey henderson'},
  {rank:185,name:'George Hendrick',value:'1111',nameLower:'george hendrick'},
  {rank:185,name:'Fred Lynn',value:'1111',nameLower:'fred lynn'},
  {rank:186,name:'Todd Zeile',value:'1110',nameLower:'todd zeile'},
  {rank:187,name:'Bryce Harper',value:'1108',nameLower:'bryce harper'},
  {rank:188,name:'Buddy Bell',value:'1106',nameLower:'buddy bell'},
  {rank:188,name:'Wally Joyner',value:'1106',nameLower:'wally joyner'},
  {rank:189,name:'Vinny Castilla',value:'1105',nameLower:'vinny castilla'},
  {rank:190,name:'Norm Cash',value:'1104',nameLower:'norm cash'},
  {rank:191,name:'Don Mattingly',value:'1099',nameLower:'don mattingly'},
  {rank:192,name:'Hal McRae',value:'1097',nameLower:'hal mcrae'},
  {rank:193,name:'Larry Doby',value:'1093',nameLower:'larry doby'},
  {rank:193,name:'Jimmy Ryan',value:'1093',nameLower:'jimmy ryan'},
  {rank:194,name:'Reggie Smith',value:'1092',nameLower:'reggie smith'},
  {rank:195,name:'Minnie Miñoso',value:'1089',nameLower:'minnie miñoso'},
  {rank:196,name:'Kent Hrbek',value:'1086',nameLower:'kent hrbek'},
  {rank:197,name:'Kirby Puckett',value:'1085',nameLower:'kirby puckett'},
  {rank:198,name:'Lou Whitaker',value:'1084',nameLower:'lou whitaker'},
  {rank:199,name:'Brian Giles',value:'1078',nameLower:'brian giles'},
  {rank:199,name:'Derrek Lee',value:'1078',nameLower:'derrek lee'},
  {rank:199,name:'Bill Terry',value:'1078',nameLower:'bill terry'},
  {rank:200,name:'José Cruz',value:'1077',nameLower:'josé cruz'},
  {rank:200,name:'Charlie Grimm',value:'1077',nameLower:'charlie grimm'},
  {rank:200,name:'Sam Rice',value:'1077',nameLower:'sam rice'},
  {rank:201,name:'Pinky Higgins',value:'1075',nameLower:'pinky higgins'},
  {rank:202,name:'Brian Downing',value:'1073',nameLower:'brian downing'},
  {rank:203,name:'Jermaine Dye',value:'1072',nameLower:'jermaine dye'},
  {rank:203,name:'Bid McPhee',value:'1072',nameLower:'bid mcphee'},
  {rank:203,name:'Greg Vaughn',value:'1072',nameLower:'greg vaughn'},
  {rank:204,name:'Jeff Conine',value:'1071',nameLower:'jeff conine'},
  {rank:204,name:'Keith Hernandez',value:'1071',nameLower:'keith hernandez'},
  {rank:204,name:'J.D. Martinez',value:'1071',nameLower:'j.d. martinez'},
  {rank:204,name:'Bob Meusel',value:'1071',nameLower:'bob meusel'},
  {rank:205,name:'Shawn Green',value:'1070',nameLower:'shawn green'},
  {rank:205,name:'Lance Parrish',value:'1070',nameLower:'lance parrish'},
  {rank:206,name:'Jimmy Dykes',value:'1069',nameLower:'jimmy dykes'},
  {rank:207,name:'Kiki Cuyler',value:'1065',nameLower:'kiki cuyler'},
  {rank:207,name:'Jorge Posada',value:'1065',nameLower:'jorge posada'},
  {rank:207,name:'Ken Singleton',value:'1065',nameLower:'ken singleton'},
  {rank:208,name:'Mo Vaughn',value:'1064',nameLower:'mo vaughn'},
  {rank:209,name:'Stuffy McInnis',value:'1063',nameLower:'stuffy mcinnis'},
  {rank:209,name:'Hack Wilson',value:'1063',nameLower:'hack wilson'},
  {rank:210,name:'Ryne Sandberg',value:'1061',nameLower:'ryne sandberg'},
  {rank:210,name:'Ryan Zimmerman',value:'1061',nameLower:'ryan zimmerman'},
  {rank:211,name:'Carl Furillo',value:'1058',nameLower:'carl furillo'},
  {rank:212,name:'Herman Long',value:'1055',nameLower:'herman long'},
  {rank:213,name:'Joe Sewell',value:'1054',nameLower:'joe sewell'},
  {rank:213,name:'Mike Trout',value:'1054',nameLower:'mike trout'},
  {rank:214,name:'Willie Davis',value:'1053',nameLower:'willie davis'},
  {rank:215,name:'Tommy Davis',value:'1052',nameLower:'tommy davis'},
  {rank:216,name:'George Scott',value:'1051',nameLower:'george scott'},
  {rank:217,name:'Joe Kuhel',value:'1049',nameLower:'joe kuhel'},
  {rank:217,name:'Salvador Perez',value:'1049',nameLower:'salvador perez'},
  {rank:218,name:'Nick Markakis',value:'1046',nameLower:'nick markakis'},
  {rank:219,name:'Ron Fairly',value:'1044',nameLower:'ron fairly'},
  {rank:220,name:'Bobby Murcer',value:'1043',nameLower:'bobby murcer'},
  {rank:221,name:'Sal Bando',value:'1039',nameLower:'sal bando'},
  {rank:222,name:'Joe Judge',value:'1034',nameLower:'joe judge'},
  {rank:223,name:'Matt Kemp',value:'1031',nameLower:'matt kemp'},
  {rank:224,name:'Michael Young',value:'1030',nameLower:'michael young'},
  {rank:225,name:'Prince Fielder',value:'1028',nameLower:'prince fielder'},
  {rank:225,name:'Ted Kluszewski',value:'1028',nameLower:'ted kluszewski'},
  {rank:226,name:'Eric Karros',value:'1027',nameLower:'eric karros'},
  {rank:227,name:'Bobby Thomson',value:'1026',nameLower:'bobby thomson'},
  {rank:228,name:'Chase Utley',value:'1025',nameLower:'chase utley'},
  {rank:229,name:'Bobby Bonds',value:'1024',nameLower:'bobby bonds'},
  {rank:230,name:'Dixie Walker',value:'1023',nameLower:'dixie walker'},
  {rank:231,name:'Travis Fryman',value:'1022',nameLower:'travis fryman'},
  {rank:231,name:'Yadier Molina',value:'1022',nameLower:'yadier molina'},
  {rank:232,name:'Bret Boone',value:'1021',nameLower:'bret boone'},
  {rank:232,name:'Fred Pfeffer',value:'1021',nameLower:'fred pfeffer'},
  {rank:233,name:'George Kelly',value:'1020',nameLower:'george kelly'},
  {rank:234,name:'Brian McCann',value:'1018',nameLower:'brian mccann'},
  {rank:235,name:'David Justice',value:'1017',nameLower:'david justice'},
  {rank:236,name:'Tim Salmon',value:'1016',nameLower:'tim salmon'},
  {rank:237,name:'Roy Campanella',value:'1015',nameLower:'roy campanella'},
  {rank:237,name:'Rod Carew',value:'1015',nameLower:'rod carew'},
  {rank:237,name:'Fred Clarke',value:'1015',nameLower:'fred clarke'},
  {rank:237,name:'Ralph Kiner',value:'1015',nameLower:'ralph kiner'},
  {rank:237,name:'George Van Haltren',value:'1015',nameLower:'george van haltren'},
  {rank:238,name:'Wade Boggs',value:'1014',nameLower:'wade boggs'},
  {rank:239,name:'Dusty Baker',value:'1013',nameLower:'dusty baker'},
  {rank:240,name:'Hal Trosky',value:'1012',nameLower:'hal trosky'},
  {rank:241,name:'Cecil Fielder',value:'1008',nameLower:'cecil fielder'},
  {rank:241,name:'Ron Gant',value:'1008',nameLower:'ron gant'},
  {rank:242,name:'Amos Otis',value:'1007',nameLower:'amos otis'},
  {rank:243,name:'Cy Williams',value:'1005',nameLower:'cy williams'},
  {rank:244,name:'Wally Pipp',value:'1004',nameLower:'wally pipp'},
  {rank:245,name:'Alan Trammell',value:'1003',nameLower:'alan trammell'},
  {rank:245,name:'Justin Upton',value:'1003',nameLower:'justin upton'},
  {rank:246,name:'George Bell',value:'1002',nameLower:'george bell'},
  {rank:247,name:'Darryl Strawberry',value:'1000',nameLower:'darryl strawberry'},
  {rank:248,name:'Gee Walker',value:'998',nameLower:'gee walker'},
  {rank:249,name:'Babe Herman',value:'997',nameLower:'babe herman'},
  {rank:250,name:'Bing Miller',value:'993',nameLower:'bing miller'},
  {rank:251,name:'Ed Konetchy',value:'992',nameLower:'ed konetchy'},
  {rank:251,name:'Marty McManus',value:'992',nameLower:'marty mcmanus'},
  {rank:251,name:'Larry Parrish',value:'992',nameLower:'larry parrish'},
  {rank:252,name:'Home Run Baker',value:'991',nameLower:'home run baker'},
  {rank:252,name:'Turkey Stearnes',value:'991',nameLower:'turkey stearnes'},
  {rank:253,name:'Ernie Lombardi',value:'990',nameLower:'ernie lombardi'},
  {rank:254,name:'Bobby Lowe',value:'989',nameLower:'bobby lowe'},
  {rank:254,name:'Bob Watson',value:'989',nameLower:'bob watson'},
  {rank:255,name:'Deacon White',value:'988',nameLower:'deacon white'},
  {rank:256,name:'Ryan Klesko',value:'987',nameLower:'ryan klesko'},
  {rank:257,name:'Justin Morneau',value:'985',nameLower:'justin morneau'},
  {rank:258,name:'Ken Caminiti',value:'983',nameLower:'ken caminiti'},
  {rank:258,name:'Jimmy Collins',value:'983',nameLower:'jimmy collins'},
  {rank:258,name:'Billy Nash',value:'983',nameLower:'billy nash'},
  {rank:258,name:'Reggie Sanders',value:'983',nameLower:'reggie sanders'},
  {rank:259,name:'José Ramírez',value:'982',nameLower:'josé ramírez'},
  {rank:260,name:'Jeromy Burnitz',value:'981',nameLower:'jeromy burnitz'},
  {rank:260,name:'Edd Roush',value:'981',nameLower:'edd roush'},
  {rank:261,name:'Tim Raines',value:'980',nameLower:'tim raines'},
  {rank:261,name:'Eugenio Suárez',value:'980',nameLower:'eugenio suárez'},
  {rank:262,name:'Del Pratt',value:'979',nameLower:'del pratt'},
  {rank:263,name:'John Anderson',value:'978',nameLower:'john anderson'},
  {rank:263,name:'Gary Matthews',value:'978',nameLower:'gary matthews'},
  {rank:264,name:'Ben Chapman',value:'977',nameLower:'ben chapman'},
  {rank:265,name:'Pat Burrell',value:'976',nameLower:'pat burrell'},
  {rank:265,name:'César Cedeño',value:'976',nameLower:'césar cedeño'},
  {rank:265,name:'Andy Pafko',value:'976',nameLower:'andy pafko'},
  {rank:266,name:'José Bautista',value:'975',nameLower:'josé bautista'},
  {rank:266,name:'Joe Gordon',value:'975',nameLower:'joe gordon'},
  {rank:267,name:'Marcell Ozuna',value:'974',nameLower:'marcell ozuna'},
  {rank:268,name:'Chris Chambliss',value:'972',nameLower:'chris chambliss'},
  {rank:269,name:'Jack Doyle',value:'971',nameLower:'jack doyle'},
  {rank:270,name:'David Wright',value:'970',nameLower:'david wright'},
  {rank:271,name:'Mike Cameron',value:'968',nameLower:'mike cameron'},
  {rank:272,name:'Marquis Grissom',value:'967',nameLower:'marquis grissom'},
  {rank:273,name:'Jay Buhner',value:'965',nameLower:'jay buhner'},
  {rank:273,name:'Anthony Rizzo',value:'965',nameLower:'anthony rizzo'},
  {rank:274,name:'Jim Wynn',value:'964',nameLower:'jim wynn'},
  {rank:275,name:'Frank Thomas',value:'962',nameLower:'frank thomas'},
  {rank:276,name:'José Abreu',value:'960',nameLower:'josé abreu'},
  {rank:276,name:'Barry Larkin',value:'960',nameLower:'barry larkin'},
  {rank:277,name:'Vernon Wells',value:'958',nameLower:'vernon wells'},
  {rank:278,name:'George Burns',value:'954',nameLower:'george burns'},
  {rank:278,name:'Frank McCormick',value:'954',nameLower:'frank mccormick'},
  {rank:279,name:'Jesse Burkett',value:'952',nameLower:'jesse burkett'},
  {rank:279,name:'Mike Lowell',value:'952',nameLower:'mike lowell'},
  {rank:280,name:'Jay Bruce',value:'951',nameLower:'jay bruce'},
  {rank:280,name:'Harry Davis',value:'951',nameLower:'harry davis'},
  {rank:280,name:'Brandon Phillips',value:'951',nameLower:'brandon phillips'},
  {rank:280,name:'Omar Vizquel',value:'951',nameLower:'omar vizquel'},
  {rank:281,name:'Dolph Camilli',value:'950',nameLower:'dolph camilli'},
  {rank:281,name:'Dave Concepción',value:'950',nameLower:'dave concepción'},
  {rank:281,name:'Troy Glaus',value:'950',nameLower:'troy glaus'},
  {rank:281,name:'King Kelly',value:'950',nameLower:'king kelly'},
  {rank:282,name:'Bill Nicholson',value:'948',nameLower:'bill nicholson'},
  {rank:283,name:'Tony Oliva',value:'947',nameLower:'tony oliva'},
  {rank:284,name:'Terry Pendleton',value:'946',nameLower:'terry pendleton'},
  {rank:285,name:'Adam Jones',value:'945',nameLower:'adam jones'},
  {rank:286,name:'Richie Sexson',value:'943',nameLower:'richie sexson'},
  {rank:287,name:'Gus Bell',value:'942',nameLower:'gus bell'},
  {rank:287,name:'Mookie Betts',value:'942',nameLower:'mookie betts'},
  {rank:287,name:'Hunter Pence',value:'942',nameLower:'hunter pence'},
  {rank:288,name:'Hal Chase',value:'941',nameLower:'hal chase'},
  {rank:289,name:'Nick Castellanos',value:'940',nameLower:'nick castellanos'},
  {rank:290,name:'Curtis Granderson',value:'937',nameLower:'curtis granderson'},
  {rank:291,name:'Nomar Garciaparra',value:'936',nameLower:'nomar garciaparra'},
  {rank:291,name:'Jimmy Rollins',value:'936',nameLower:'jimmy rollins'},
  {rank:292,name:'Eric Davis',value:'934',nameLower:'eric davis'},
  {rank:292,name:'Larry Gardner',value:'934',nameLower:'larry gardner'},
  {rank:293,name:'Tommy Tucker',value:'932',nameLower:'tommy tucker'},
  {rank:294,name:'Travis Jackson',value:'929',nameLower:'travis jackson'},
  {rank:294,name:'Jackie Jensen',value:'929',nameLower:'jackie jensen'},
  {rank:295,name:'Pinky Whitney',value:'927',nameLower:'pinky whitney'},
  {rank:296,name:'Arky Vaughan',value:'926',nameLower:'arky vaughan'},
  {rank:297,name:'Danny Tartabull',value:'925',nameLower:'danny tartabull'},
  {rank:298,name:'Deron Johnson',value:'923',nameLower:'deron johnson'},
  {rank:298,name:'Joe Mauer',value:'923',nameLower:'joe mauer'},
  {rank:298,name:'Édgar Rentería',value:'923',nameLower:'édgar rentería'},
  {rank:299,name:'Phil Cavarretta',value:'920',nameLower:'phil cavarretta'},
  {rank:299,name:'Benito Santiago',value:'920',nameLower:'benito santiago'},
  {rank:300,name:'Tom Brunansky',value:'919',nameLower:'tom brunansky'},
  {rank:301,name:'Toby Harrah',value:'918',nameLower:'toby harrah'},
  {rank:302,name:'Hanley Ramírez',value:'917',nameLower:'hanley ramírez'},
  {rank:303,name:'Duke Farrell',value:'916',nameLower:'duke farrell'},
  {rank:303,name:'Ken Williams',value:'916',nameLower:'ken williams'},
  {rank:304,name:'Jose Altuve',value:'914',nameLower:'jose altuve'},
  {rank:305,name:'Mule Suttles',value:'913',nameLower:'mule suttles'},
  {rank:306,name:'Harry Stovey',value:'912',nameLower:'harry stovey'},
  {rank:307,name:'Ian Kinsler',value:'909',nameLower:'ian kinsler'},
  {rank:307,name:'A.J. Pierzynski',value:'909',nameLower:'a.j. pierzynski'},
  {rank:307,name:'Mike Sweeney',value:'909',nameLower:'mike sweeney'},
  {rank:308,name:'Aubrey Huff',value:'904',nameLower:'aubrey huff'},
  {rank:309,name:'Eric Chavez',value:'902',nameLower:'eric chavez'},
  {rank:310,name:'Ben Oglivie',value:'901',nameLower:'ben oglivie'},
  {rank:311,name:'Lou Brock',value:'900',nameLower:'lou brock'},
  {rank:311,name:'Steve Brodie',value:'900',nameLower:'steve brodie'},
  {rank:312,name:'Matt Stairs',value:'899',nameLower:'matt stairs'},
  {rank:313,name:'Wally Berger',value:'898',nameLower:'wally berger'},
  {rank:313,name:'Pedro Guerrero',value:'898',nameLower:'pedro guerrero'},
  {rank:314,name:'Andre Thornton',value:'895',nameLower:'andre thornton'},
  {rank:315,name:'Eric Hosmer',value:'893',nameLower:'eric hosmer'},
  {rank:316,name:'Rico Carty',value:'890',nameLower:'rico carty'},
  {rank:316,name:'Richie Hebner',value:'890',nameLower:'richie hebner'},
  {rank:317,name:'Bill Skowron',value:'888',nameLower:'bill skowron'},
  {rank:318,name:'José Guillén',value:'887',nameLower:'josé guillén'},
  {rank:318,name:'Jeff Heath',value:'887',nameLower:'jeff heath'},
  {rank:319,name:'Frank White',value:'886',nameLower:'frank white'},
  {rank:320,name:'Pee Wee Reese',value:'885',nameLower:'pee wee reese'},
  {rank:321,name:'Tony Cuccinello',value:'884',nameLower:'tony cuccinello'},
  {rank:321,name:'Chet Lemon',value:'884',nameLower:'chet lemon'},
  {rank:321,name:'Rabbit Maranville',value:'884',nameLower:'rabbit maranville'},
  {rank:322,name:'Charlie Comiskey',value:'883',nameLower:'charlie comiskey'},
  {rank:322,name:'Buck Ewing',value:'883',nameLower:'buck ewing'},
  {rank:323,name:'Jeff Burroughs',value:'882',nameLower:'jeff burroughs'},
  {rank:323,name:'Adam LaRoche',value:'882',nameLower:'adam laroche'},
  {rank:324,name:'Doug DeCinces',value:'879',nameLower:'doug decinces'},
  {rank:324,name:'John Mayberry',value:'879',nameLower:'john mayberry'},
  {rank:324,name:'Christian Yelich',value:'879',nameLower:'christian yelich'},
  {rank:325,name:'Willie Wells',value:'878',nameLower:'willie wells'},
  {rank:326,name:'J.T. Snow',value:'877',nameLower:'j.t. snow'},
  {rank:327,name:'Hank Sauer',value:'876',nameLower:'hank sauer'},
  {rank:328,name:'Ray Durham',value:'875',nameLower:'ray durham'},
  {rank:329,name:'Ray Lankford',value:'874',nameLower:'ray lankford'},
  {rank:329,name:'Carney Lansford',value:'874',nameLower:'carney lansford'},
  {rank:329,name:'Joe Vosmik',value:'874',nameLower:'joe vosmik'},
  {rank:330,name:'Jhonny Peralta',value:'873',nameLower:'jhonny peralta'},
  {rank:331,name:'Xander Bogaerts',value:'871',nameLower:'xander bogaerts'},
  {rank:331,name:'Mark Reynolds',value:'871',nameLower:'mark reynolds'},
  {rank:332,name:'Kirk Gibson',value:'870',nameLower:'kirk gibson'},
  {rank:332,name:'George Kell',value:'870',nameLower:'george kell'},
  {rank:332,name:'Bill White',value:'870',nameLower:'bill white'},
  {rank:333,name:'Asdrúbal Cabrera',value:'869',nameLower:'asdrúbal cabrera'},
  {rank:333,name:'John Ward',value:'869',nameLower:'john ward'},
  {rank:334,name:'Aaron Judge',value:'868',nameLower:'aaron judge'},
  {rank:335,name:'Francisco Lindor',value:'866',nameLower:'francisco lindor'},
  {rank:336,name:'Cliff Floyd',value:'865',nameLower:'cliff floyd'},
  {rank:336,name:'Matt Olson',value:'865',nameLower:'matt olson'},
  {rank:337,name:'Bobby Grich',value:'864',nameLower:'bobby grich'},
  {rank:337,name:'Javy López',value:'864',nameLower:'javy lópez'},
  {rank:338,name:'Jay Bell',value:'860',nameLower:'jay bell'},
  {rank:338,name:'Bill Madlock',value:'860',nameLower:'bill madlock'},
  {rank:338,name:'Raúl Mondesí',value:'860',nameLower:'raúl mondesí'},
  {rank:339,name:'Jack Fournier',value:'859',nameLower:'jack fournier'},
  {rank:339,name:'Ken Griffey',value:'859',nameLower:'ken griffey'},
  {rank:340,name:'Willie McGee',value:'856',nameLower:'willie mcgee'},
  {rank:341,name:'Paul Hines',value:'855',nameLower:'paul hines'},
  {rank:342,name:'Melky Cabrera',value:'854',nameLower:'melky cabrera'},
  {rank:342,name:'Orlando Cabrera',value:'854',nameLower:'orlando cabrera'},
  {rank:343,name:'Bill Mazeroski',value:'853',nameLower:'bill mazeroski'},
  {rank:343,name:'Mike Tiernan',value:'853',nameLower:'mike tiernan'},
  {rank:344,name:'Felipe Alou',value:'852',nameLower:'felipe alou'},
  {rank:344,name:'Ken Keltner',value:'852',nameLower:'ken keltner'},
  {rank:345,name:'Roger Maris',value:'850',nameLower:'roger maris'},
  {rank:346,name:'Dean Palmer',value:'849',nameLower:'dean palmer'},
  {rank:347,name:'Ossie Bluege',value:'848',nameLower:'ossie bluege'},
  {rank:347,name:'Buddy Myer',value:'848',nameLower:'buddy myer'},
  {rank:348,name:'Devon White',value:'846',nameLower:'devon white'},
  {rank:349,name:'Tony Fernández',value:'844',nameLower:'tony fernández'},
  {rank:350,name:'Doc Cramer',value:'842',nameLower:'doc cramer'},
  {rank:351,name:'Johnny Callison',value:'840',nameLower:'johnny callison'},
  {rank:351,name:'Hughie Jennings',value:'840',nameLower:'hughie jennings'},
  {rank:351,name:'Deacon McGuire',value:'840',nameLower:'deacon mcguire'},
  {rank:352,name:'Lou Bierbauer',value:'839',nameLower:'lou bierbauer'},
  {rank:352,name:'Billy Herman',value:'839',nameLower:'billy herman'},
  {rank:352,name:'Kyle Schwarber',value:'839',nameLower:'kyle schwarber'},
  {rank:353,name:'Sam West',value:'838',nameLower:'sam west'},
  {rank:354,name:'Henry Larkin',value:'836',nameLower:'henry larkin'},
  {rank:355,name:'Thomas Burns',value:'834',nameLower:'thomas burns'},
  {rank:356,name:'Chick Hafey',value:'833',nameLower:'chick hafey'},
  {rank:357,name:'Justin Turner',value:'832',nameLower:'justin turner'},
  {rank:358,name:'Mickey Cochrane',value:'830',nameLower:'mickey cochrane'},
  {rank:358,name:'Augie Galan',value:'830',nameLower:'augie galan'},
  {rank:358,name:'Marcus Semien',value:'830',nameLower:'marcus semien'},
  {rank:358,name:'Gene Woodling',value:'830',nameLower:'gene woodling'},
  {rank:359,name:'Harlond Clift',value:'829',nameLower:'harlond clift'},
  {rank:360,name:'Hardy Richardson',value:'828',nameLower:'hardy richardson'},
  {rank:361,name:'Jack Glasscock',value:'827',nameLower:'jack glasscock'},
  {rank:361,name:'Willie Kamm',value:'827',nameLower:'willie kamm'},
  {rank:362,name:'Bob Boone',value:'826',nameLower:'bob boone'},
  {rank:362,name:'Darrell Porter',value:'826',nameLower:'darrell porter'},
  {rank:363,name:'Hubie Brooks',value:'824',nameLower:'hubie brooks'},
  {rank:363,name:'Tony Clark',value:'824',nameLower:'tony clark'},
  {rank:363,name:'Kid Gleason',value:'824',nameLower:'kid gleason'},
  {rank:363,name:'Claudell Washington',value:'824',nameLower:'claudell washington'},
  {rank:364,name:'Brian Jordan',value:'821',nameLower:'brian jordan'},
  {rank:365,name:'Irish Meusel',value:'819',nameLower:'irish meusel'},
  {rank:365,name:'Tony Phillips',value:'819',nameLower:'tony phillips'},
  {rank:366,name:'Baby Doll Jacobson',value:'818',nameLower:'baby doll jacobson'},
  {rank:366,name:'Carlos Peña',value:'818',nameLower:'carlos peña'},
  {rank:366,name:'Gus Suhr',value:'818',nameLower:'gus suhr'},
  {rank:367,name:'George Springer',value:'817',nameLower:'george springer'},
  {rank:368,name:'Oscar Charleston',value:'816',nameLower:'oscar charleston'},
  {rank:368,name:'Josh Donaldson',value:'816',nameLower:'josh donaldson'},
  {rank:368,name:'Harry Hooper',value:'816',nameLower:'harry hooper'},
  {rank:368,name:'Juan Uribe',value:'816',nameLower:'juan uribe'},
  {rank:368,name:'José Valentín',value:'816',nameLower:'josé valentín'},
  {rank:369,name:'Tony Armas',value:'815',nameLower:'tony armas'},
  {rank:370,name:'Walker Cooper',value:'812',nameLower:'walker cooper'},
  {rank:370,name:'Willie Jones',value:'812',nameLower:'willie jones'},
  {rank:370,name:'Tommy Leach',value:'812',nameLower:'tommy leach'},
  {rank:371,name:'Tom Daly',value:'811',nameLower:'tom daly'},
  {rank:372,name:'Willie Keeler',value:'810',nameLower:'willie keeler'},
  {rank:372,name:'Joe Rudi',value:'810',nameLower:'joe rudi'},
  {rank:372,name:'Jimmy Sheckard',value:'810',nameLower:'jimmy sheckard'},
  {rank:373,name:'Sherm Lollar',value:'808',nameLower:'sherm lollar'},
  {rank:374,name:'Kevin McReynolds',value:'807',nameLower:'kevin mcreynolds'},
  {rank:374,name:'Kyle Seager',value:'807',nameLower:'kyle seager'},
  {rank:375,name:'Sid Gordon',value:'805',nameLower:'sid gordon'},
  {rank:376,name:'Nick Swisher',value:'803',nameLower:'nick swisher'},
  {rank:377,name:'Max Carey',value:'802',nameLower:'max carey'},
  {rank:377,name:'Willie Montañez',value:'802',nameLower:'willie montañez'},
  {rank:378,name:'Charlie Blackmon',value:'801',nameLower:'charlie blackmon'},
  {rank:379,name:'Joe Quinn',value:'800',nameLower:'joe quinn'},
  {rank:379,name:'Germany Smith',value:'800',nameLower:'germany smith'},
  {rank:380,name:'Red Kress',value:'799',nameLower:'red kress'},
  {rank:380,name:'Cy Seymour',value:'799',nameLower:'cy seymour'},
  {rank:380,name:'Jayson Werth',value:'799',nameLower:'jayson werth'},
  {rank:380,name:'Heinie Zimmerman',value:'799',nameLower:'heinie zimmerman'},
  {rank:381,name:'Bob Allison',value:'796',nameLower:'bob allison'},
  {rank:381,name:'Jimmy Williams',value:'796',nameLower:'jimmy williams'},
  {rank:382,name:'J.D. Drew',value:'795',nameLower:'j.d. drew'},
  {rank:382,name:'Tommy Henrich',value:'795',nameLower:'tommy henrich'},
  {rank:383,name:'Michael Cuddyer',value:'794',nameLower:'michael cuddyer'},
  {rank:383,name:'Rafael Devers',value:'794',nameLower:'rafael devers'},
  {rank:383,name:'Larry Doyle',value:'794',nameLower:'larry doyle'},
  {rank:383,name:'George McQuinn',value:'794',nameLower:'george mcquinn'},
  {rank:383,name:'Alex Ríos',value:'794',nameLower:'alex ríos'},
  {rank:384,name:'Frank Schulte',value:'793',nameLower:'frank schulte'},
  {rank:384,name:'Ozzie Smith',value:'793',nameLower:'ozzie smith'},
  {rank:385,name:'Carl Everett',value:'792',nameLower:'carl everett'},
  {rank:385,name:'Joe Jackson',value:'792',nameLower:'joe jackson'},
  {rank:385,name:'Andy Van Slyke',value:'792',nameLower:'andy van slyke'},
  {rank:385,name:'Richie Zisk',value:'792',nameLower:'richie zisk'},
  {rank:386,name:'Luis Aparicio',value:'791',nameLower:'luis aparicio'},
  {rank:386,name:'Duffy Lewis',value:'791',nameLower:'duffy lewis'},
  {rank:387,name:'Nellie Fox',value:'790',nameLower:'nellie fox'},
  {rank:388,name:'Lou Boudreau',value:'789',nameLower:'lou boudreau'},
  {rank:389,name:'Carlos González',value:'785',nameLower:'carlos gonzález'},
  {rank:389,name:'Joe Tinker',value:'785',nameLower:'joe tinker'},
  {rank:390,name:'Bibb Falk',value:'784',nameLower:'bibb falk'},
  {rank:391,name:'Shin-Soo Choo',value:'782',nameLower:'shin-soo choo'},
  {rank:391,name:'Gorman Thomas',value:'782',nameLower:'gorman thomas'},
  {rank:391,name:'Jason Thompson',value:'782',nameLower:'jason thompson'},
  {rank:392,name:'Kenny Lofton',value:'781',nameLower:'kenny lofton'},
  {rank:393,name:'Chris Davis',value:'780',nameLower:'chris davis'},
  {rank:393,name:'Ichiro Suzuki',value:'780',nameLower:'ichiro suzuki'},
  {rank:393,name:'Troy Tulowitzki',value:'780',nameLower:'troy tulowitzki'},
  {rank:394,name:'Freddie Lindstrom',value:'779',nameLower:'freddie lindstrom'},
  {rank:394,name:'Kip Selbach',value:'779',nameLower:'kip selbach'},
  {rank:395,name:'Gus Zernial',value:'776',nameLower:'gus zernial'},
  {rank:396,name:'Elvis Andrus',value:'775',nameLower:'elvis andrus'},
  {rank:396,name:'José Cardenal',value:'775',nameLower:'josé cardenal'},
  {rank:396,name:'Elston Howard',value:'775',nameLower:'elston howard'},
  {rank:396,name:'Rick Monday',value:'775',nameLower:'rick monday'},
  {rank:397,name:'Carlos Baerga',value:'774',nameLower:'carlos baerga'},
  {rank:398,name:'Bob Bailey',value:'773',nameLower:'bob bailey'},
  {rank:398,name:'Sam Chapman',value:'773',nameLower:'sam chapman'},
  {rank:398,name:'Rico Petrocelli',value:'773',nameLower:'rico petrocelli'},
  {rank:398,name:'Red Schoendienst',value:'773',nameLower:'red schoendienst'},
  {rank:398,name:'Riggs Stephenson',value:'773',nameLower:'riggs stephenson'},
  {rank:399,name:'Pete Alonso',value:'772',nameLower:'pete alonso'},
  {rank:399,name:'Bill Hallman',value:'772',nameLower:'bill hallman'},
  {rank:400,name:'Russell Martin',value:'771',nameLower:'russell martin'},
  {rank:401,name:'Josh Gibson',value:'769',nameLower:'josh gibson'},
  {rank:402,name:'Rondell White',value:'768',nameLower:'rondell white'},
  {rank:402,name:'Ben Zobrist',value:'768',nameLower:'ben zobrist'},
  {rank:403,name:'Bruce Campbell',value:'766',nameLower:'bruce campbell'},
  {rank:403,name:'Carl Crawford',value:'766',nameLower:'carl crawford'},
  {rank:403,name:'Lou Piniella',value:'766',nameLower:'lou piniella'},
  {rank:404,name:'Jackie Robinson',value:'765',nameLower:'jackie robinson'},
  {rank:405,name:'Dan Driessen',value:'763',nameLower:'dan driessen'},
  {rank:406,name:'Harry Steinfeldt',value:'762',nameLower:'harry steinfeldt'},
  {rank:407,name:'Brady Anderson',value:'761',nameLower:'brady anderson'},
  {rank:408,name:'Howard Johnson',value:'760',nameLower:'howard johnson'},
  {rank:408,name:'Charlie Keller',value:'760',nameLower:'charlie keller'},
  {rank:408,name:'Hideki Matsui',value:'760',nameLower:'hideki matsui'},
  {rank:408,name:'Kevin Mitchell',value:'760',nameLower:'kevin mitchell'},
  {rank:409,name:'Billy Shindle',value:'759',nameLower:'billy shindle'},
  {rank:410,name:'Bill Freehan',value:'758',nameLower:'bill freehan'},
  {rank:410,name:'Roy White',value:'758',nameLower:'roy white'},
  {rank:411,name:'Alex Bregman',value:'757',nameLower:'alex bregman'},
  {rank:411,name:'Al Dark',value:'757',nameLower:'al dark'},
  {rank:411,name:'Ramón Hernández',value:'757',nameLower:'ramón hernández'},
  {rank:411,name:'Tip O\'Neill',value:'757',nameLower:'tip o\'neill'},
  {rank:411,name:'Jason Varitek',value:'757',nameLower:'jason varitek'},
  {rank:412,name:'Rich Aurilia',value:'756',nameLower:'rich aurilia'},
  {rank:412,name:'Elmer Flick',value:'756',nameLower:'elmer flick'},
  {rank:412,name:'Denny Lyons',value:'756',nameLower:'denny lyons'},
  {rank:413,name:'Jason Bay',value:'754',nameLower:'jason bay'},
  {rank:413,name:'Garry Maddox',value:'754',nameLower:'garry maddox'},
  {rank:413,name:'Melvin Mora',value:'754',nameLower:'melvin mora'},
  {rank:414,name:'Dave Foutz',value:'750',nameLower:'dave foutz'},
  {rank:415,name:'Alex Gordon',value:'749',nameLower:'alex gordon'},
  {rank:416,name:'Brandon Crawford',value:'748',nameLower:'brandon crawford'},
  {rank:417,name:'Cody Bellinger',value:'745',nameLower:'cody bellinger'},
  {rank:417,name:'Jorge Orta',value:'745',nameLower:'jorge orta'},
  {rank:417,name:'Earl Sheely',value:'745',nameLower:'earl sheely'},
  {rank:417,name:'Terry Steinbach',value:'745',nameLower:'terry steinbach'},
  {rank:418,name:'Edgardo Alfonzo',value:'744',nameLower:'edgardo alfonzo'},
  {rank:418,name:'Jason Kendall',value:'744',nameLower:'jason kendall'},
  {rank:418,name:'Mike Napoli',value:'744',nameLower:'mike napoli'},
  {rank:419,name:'Cupid Childs',value:'743',nameLower:'cupid childs'},
  {rank:419,name:'Phil Nevin',value:'743',nameLower:'phil nevin'},
  {rank:419,name:'Juan Soto',value:'743',nameLower:'juan soto'},
  {rank:419,name:'Dick Stuart',value:'743',nameLower:'dick stuart'},
  {rank:420,name:'Tom Brown',value:'742',nameLower:'tom brown'},
  {rank:420,name:'Billy Hamilton',value:'742',nameLower:'billy hamilton'},
  {rank:421,name:'Carlos Correa',value:'740',nameLower:'carlos correa'},
  {rank:421,name:'Charlie Hayes',value:'740',nameLower:'charlie hayes'},
  {rank:421,name:'Fred Merkle',value:'740',nameLower:'fred merkle'},
  {rank:421,name:'Kendrys Morales',value:'740',nameLower:'kendrys morales'},
  {rank:421,name:'Roger Peckinpaugh',value:'740',nameLower:'roger peckinpaugh'},
  {rank:421,name:'John Reilly',value:'740',nameLower:'john reilly'},
  {rank:421,name:'Earl Torgeson',value:'740',nameLower:'earl torgeson'},
  {rank:422,name:'Joe Randa',value:'739',nameLower:'joe randa'},
  {rank:423,name:'Patsy Donovan',value:'738',nameLower:'patsy donovan'},
  {rank:423,name:'Phil Garner',value:'738',nameLower:'phil garner'},
  {rank:423,name:'Jack O\'Connor',value:'738',nameLower:'jack o\'connor'},
  {rank:424,name:'Ray Boone',value:'737',nameLower:'ray boone'},
  {rank:424,name:'Lloyd Moseby',value:'737',nameLower:'lloyd moseby'},
  {rank:425,name:'Josh Bell',value:'736',nameLower:'josh bell'},
  {rank:425,name:'Pete O\'Brien',value:'736',nameLower:'pete o\'brien'},
  {rank:426,name:'Sean Casey',value:'735',nameLower:'sean casey'},
  {rank:426,name:'Daniel Murphy',value:'735',nameLower:'daniel murphy'},
  {rank:426,name:'Patsy Tebeau',value:'735',nameLower:'patsy tebeau'},
  {rank:427,name:'Rick Ferrell',value:'734',nameLower:'rick ferrell'},
  {rank:427,name:'Jud Wilson',value:'734',nameLower:'jud wilson'},
  {rank:428,name:'Geoff Jenkins',value:'733',nameLower:'geoff jenkins'},
  {rank:429,name:'Tommy McCarthy',value:'732',nameLower:'tommy mccarthy'},
  {rank:429,name:'Mickey Tettleton',value:'732',nameLower:'mickey tettleton'},
  {rank:430,name:'Travis Hafner',value:'731',nameLower:'travis hafner'},
  {rank:431,name:'Jason Heyward',value:'730',nameLower:'jason heyward'},
  {rank:431,name:'Kurt Suzuki',value:'730',nameLower:'kurt suzuki'},
  {rank:432,name:'Don Money',value:'729',nameLower:'don money'},
  {rank:432,name:'Dave Philley',value:'729',nameLower:'dave philley'},
  {rank:432,name:'Buster Posey',value:'729',nameLower:'buster posey'},
  {rank:433,name:'Billy Butler',value:'728',nameLower:'billy butler'},
  {rank:433,name:'Frank Malzone',value:'728',nameLower:'frank malzone'},
  {rank:433,name:'Garry Templeton',value:'728',nameLower:'garry templeton'},
  {rank:434,name:'Jeff Cirillo',value:'727',nameLower:'jeff cirillo'},
  {rank:434,name:'Dan McGann',value:'727',nameLower:'dan mcgann'},
  {rank:435,name:'Mike Greenwell',value:'726',nameLower:'mike greenwell'},
  {rank:436,name:'Billy Hoy',value:'725',nameLower:'billy hoy'},
  {rank:436,name:'Dustin Pedroia',value:'725',nameLower:'dustin pedroia'},
  {rank:437,name:'Howie Kendrick',value:'724',nameLower:'howie kendrick'},
  {rank:437,name:'Shohei Ohtani',value:'724',nameLower:'shohei ohtani'},
  {rank:438,name:'Royce Clayton',value:'723',nameLower:'royce clayton'},
  {rank:438,name:'Jeffrey Leonard',value:'723',nameLower:'jeffrey leonard'},
  {rank:438,name:'Adam Lind',value:'723',nameLower:'adam lind'},
  {rank:438,name:'Plácido Polanco',value:'723',nameLower:'plácido polanco'},
  {rank:438,name:'Eddie Robinson',value:'723',nameLower:'eddie robinson'},
  {rank:438,name:'Glenn Wright',value:'723',nameLower:'glenn wright'},
  {rank:439,name:'Jake Daubert',value:'722',nameLower:'jake daubert'},
  {rank:439,name:'Doug Rader',value:'722',nameLower:'doug rader'},
  {rank:439,name:'Wilbert Robinson',value:'722',nameLower:'wilbert robinson'},
  {rank:440,name:'Sam Mertes',value:'721',nameLower:'sam mertes'},
  {rank:440,name:'Joe Pepitone',value:'721',nameLower:'joe pepitone'},
  {rank:441,name:'Michael Brantley',value:'720',nameLower:'michael brantley'},
  {rank:441,name:'Mike Griffin',value:'720',nameLower:'mike griffin'},
  {rank:441,name:'Mark Kotsay',value:'720',nameLower:'mark kotsay'},
  {rank:441,name:'Chris Speier',value:'720',nameLower:'chris speier'},
  {rank:442,name:'Gavy Cravath',value:'719',nameLower:'gavy cravath'},
  {rank:442,name:'José Reyes',value:'719',nameLower:'josé reyes'},
  {rank:443,name:'Tony Batista',value:'718',nameLower:'tony batista'},
  {rank:444,name:'Al Cowens',value:'717',nameLower:'al cowens'},
  {rank:444,name:'Al Rosen',value:'717',nameLower:'al rosen'},
  {rank:445,name:'Jesse Barfield',value:'716',nameLower:'jesse barfield'},
  {rank:446,name:'Dots Miller',value:'714',nameLower:'dots miller'},
  {rank:447,name:'Buck Freeman',value:'713',nameLower:'buck freeman'},
  {rank:448,name:'George Grantham',value:'712',nameLower:'george grantham'},
  {rank:449,name:'Ian Desmond',value:'711',nameLower:'ian desmond'},
  {rank:449,name:'Bengie Molina',value:'711',nameLower:'bengie molina'},
  {rank:450,name:'Dick Bartell',value:'710',nameLower:'dick bartell'},
  {rank:450,name:'Marlon Byrd',value:'710',nameLower:'marlon byrd'},
  {rank:450,name:'John Stone',value:'710',nameLower:'john stone'},
  {rank:451,name:'Bobby Higginson',value:'709',nameLower:'bobby higginson'},
  {rank:451,name:'Jeff King',value:'709',nameLower:'jeff king'},
  {rank:452,name:'Shano Collins',value:'708',nameLower:'shano collins'},
  {rank:452,name:'Granny Hamner',value:'708',nameLower:'granny hamner'},
  {rank:452,name:'Dave Henderson',value:'708',nameLower:'dave henderson'},
  {rank:452,name:'Tony Peña',value:'708',nameLower:'tony peña'},
  {rank:453,name:'Dick Groat',value:'707',nameLower:'dick groat'},
  {rank:454,name:'Jim Fregosi',value:'706',nameLower:'jim fregosi'},
  {rank:454,name:'Dan Uggla',value:'706',nameLower:'dan uggla'},
  {rank:455,name:'Wally Schang',value:'705',nameLower:'wally schang'},
  {rank:456,name:'Zeke Bonura',value:'704',nameLower:'zeke bonura'},
  {rank:456,name:'Walt Dropo',value:'704',nameLower:'walt dropo'},
  {rank:456,name:'J.T. Realmuto',value:'704',nameLower:'j.t. realmuto'},
  {rank:457,name:'Hank Bauer',value:'703',nameLower:'hank bauer'},
  {rank:457,name:'Juan Samuel',value:'703',nameLower:'juan samuel'},
  {rank:458,name:'Danny Murphy',value:'702',nameLower:'danny murphy'},
  {rank:458,name:'Mike Stanley',value:'702',nameLower:'mike stanley'},
  {rank:459,name:'Josh Hamilton',value:'701',nameLower:'josh hamilton'},
  {rank:459,name:'Thurman Munson',value:'701',nameLower:'thurman munson'},
  {rank:459,name:'Al Smith',value:'701',nameLower:'al smith'},
  {rank:460,name:'Darin Erstad',value:'699',nameLower:'darin erstad'},
  {rank:460,name:'Cliff Johnson',value:'699',nameLower:'cliff johnson'},
  {rank:460,name:'Kevin Millar',value:'699',nameLower:'kevin millar'},
  {rank:460,name:'Wally Post',value:'699',nameLower:'wally post'},
  {rank:460,name:'Carl Reynolds',value:'699',nameLower:'carl reynolds'},
  {rank:461,name:'Jeff Francoeur',value:'698',nameLower:'jeff francoeur'},
  {rank:461,name:'Luke Sewell',value:'698',nameLower:'luke sewell'},
  {rank:462,name:'Teoscar Hernández',value:'697',nameLower:'teoscar hernández'},
  {rank:463,name:'Von Hayes',value:'696',nameLower:'von hayes'},
  {rank:463,name:'Dick McAuliffe',value:'696',nameLower:'dick mcauliffe'},
  {rank:463,name:'Milt Stock',value:'696',nameLower:'milt stock'},
  {rank:464,name:'Lu Blue',value:'695',nameLower:'lu blue'},
  {rank:464,name:'Aaron Hill',value:'695',nameLower:'aaron hill'},
  {rank:465,name:'Roy Smalley',value:'694',nameLower:'roy smalley'},
  {rank:466,name:'Pete Fox',value:'693',nameLower:'pete fox'},
  {rank:466,name:'Monte Irvin',value:'693',nameLower:'monte irvin'},
  {rank:466,name:'George LaChance',value:'693',nameLower:'george lachance'},
  {rank:467,name:'Corey Seager',value:'692',nameLower:'corey seager'},
  {rank:468,name:'Javier Báez',value:'691',nameLower:'javier báez'},
  {rank:468,name:'Dansby Swanson',value:'691',nameLower:'dansby swanson'},
  {rank:469,name:'Álex González',value:'690',nameLower:'álex gonzález'},
  {rank:470,name:'Leo Cárdenas',value:'689',nameLower:'leo cárdenas'},
  {rank:471,name:'J.J. Hardy',value:'688',nameLower:'j.j. hardy'},
  {rank:471,name:'Fred Tenney',value:'688',nameLower:'fred tenney'},
  {rank:471,name:'Curt Walker',value:'688',nameLower:'curt walker'},
  {rank:472,name:'Jack Clements',value:'687',nameLower:'jack clements'},
  {rank:472,name:'Andre Ethier',value:'687',nameLower:'andre ethier'},
  {rank:472,name:'Willie Randolph',value:'687',nameLower:'willie randolph'},
  {rank:473,name:'Mike Hargrove',value:'686',nameLower:'mike hargrove'},
  {rank:474,name:'Bob Horner',value:'685',nameLower:'bob horner'},
  {rank:475,name:'Damion Easley',value:'684',nameLower:'damion easley'},
  {rank:475,name:'David Segui',value:'684',nameLower:'david segui'},
  {rank:476,name:'Tom Burns',value:'683',nameLower:'tom burns'},
  {rank:476,name:'Alvin Davis',value:'683',nameLower:'alvin davis'},
  {rank:476,name:'Mike Moustakas',value:'683',nameLower:'mike moustakas'},
  {rank:476,name:'Dmitri Young',value:'683',nameLower:'dmitri young'},
  {rank:477,name:'Donn Clendenon',value:'682',nameLower:'donn clendenon'},
  {rank:477,name:'Eddie Yost',value:'682',nameLower:'eddie yost'},
  {rank:478,name:'Wally Moses',value:'679',nameLower:'wally moses'},
  {rank:478,name:'Tillie Walker',value:'679',nameLower:'tillie walker'},
  {rank:479,name:'Starlin Castro',value:'678',nameLower:'starlin castro'},
  {rank:480,name:'Art Fletcher',value:'676',nameLower:'art fletcher'},
  {rank:480,name:'Starling Marte',value:'676',nameLower:'starling marte'},
  {rank:481,name:'Lyle Overbay',value:'675',nameLower:'lyle overbay'},
  {rank:481,name:'Claude Ritchey',value:'675',nameLower:'claude ritchey'},
  {rank:482,name:'Larry Hisle',value:'674',nameLower:'larry hisle'},
  {rank:482,name:'Keith Moreland',value:'674',nameLower:'keith moreland'},
  {rank:482,name:'Gene Tenace',value:'674',nameLower:'gene tenace'},
  {rank:483,name:'Smoky Burgess',value:'673',nameLower:'smoky burgess'},
  {rank:484,name:'Ezra Sutton',value:'672',nameLower:'ezra sutton'},
  {rank:484,name:'Trea Turner',value:'672',nameLower:'trea turner'},
  {rank:484,name:'Sam Wise',value:'672',nameLower:'sam wise'},
  {rank:485,name:'Harvey Kuenn',value:'671',nameLower:'harvey kuenn'},
  {rank:485,name:'Anthony Rendon',value:'671',nameLower:'anthony rendon'},
  {rank:486,name:'James Loney',value:'669',nameLower:'james loney'},
  {rank:486,name:'Leon Wagner',value:'669',nameLower:'leon wagner'},
  {rank:487,name:'Derek Bell',value:'668',nameLower:'derek bell'},
  {rank:487,name:'Shawon Dunston',value:'668',nameLower:'shawon dunston'},
  {rank:487,name:'Preston Wilson',value:'668',nameLower:'preston wilson'},
  {rank:488,name:'Jerry Denny',value:'667',nameLower:'jerry denny'},
  {rank:488,name:'Juan Encarnación',value:'667',nameLower:'juan encarnación'},
  {rank:488,name:'Ed Williamson',value:'667',nameLower:'ed williamson'},
  {rank:489,name:'Oscar Gamble',value:'666',nameLower:'oscar gamble'},
  {rank:490,name:'Elmer Smith',value:'665',nameLower:'elmer smith'},
  {rank:491,name:'Gregg Jefferies',value:'663',nameLower:'gregg jefferies'},
  {rank:491,name:'DJ LeMahieu',value:'663',nameLower:'dj lemahieu'},
  {rank:492,name:'Randy Winn',value:'662',nameLower:'randy winn'},
  {rank:493,name:'Wally Moon',value:'661',nameLower:'wally moon'},
  {rank:494,name:'Carlos Guillén',value:'660',nameLower:'carlos guillén'},
  {rank:495,name:'Pete Browning',value:'659',nameLower:'pete browning'},
  {rank:495,name:'Matt Carpenter',value:'659',nameLower:'matt carpenter'},
  {rank:495,name:'Ripper Collins',value:'659',nameLower:'ripper collins'},
  {rank:496,name:'Bruce Bochte',value:'658',nameLower:'bruce bochte'},
  {rank:496,name:'Vic Power',value:'658',nameLower:'vic power'},
  {rank:497,name:'Del Crandall',value:'657',nameLower:'del crandall'},
  {rank:497,name:'Bones Ely',value:'657',nameLower:'bones ely'},
  {rank:497,name:'Cecil Travis',value:'657',nameLower:'cecil travis'},
  {rank:498,name:'Tito Francona',value:'656',nameLower:'tito francona'},
  {rank:498,name:'Billy Jurges',value:'656',nameLower:'billy jurges'},
  {rank:499,name:'Pete Incaviglia',value:'655',nameLower:'pete incaviglia'},
  {rank:499,name:'Trevor Story',value:'655',nameLower:'trevor story'},
  {rank:500,name:'Clete Boyer',value:'654',nameLower:'clete boyer'},
  {rank:500,name:'José Vidro',value:'654',nameLower:'josé vidro'},
  {rank:501,name:'George Cutshaw',value:'653',nameLower:'george cutshaw'},
  {rank:502,name:'Randal Grichuk',value:'652',nameLower:'randal grichuk'},
  {rank:502,name:'Al Lopez',value:'652',nameLower:'al lopez'},
  {rank:503,name:'Frankie Crosetti',value:'649',nameLower:'frankie crosetti'},
  {rank:504,name:'Brandon Inge',value:'648',nameLower:'brandon inge'},
  {rank:504,name:'Aurelio Rodríguez',value:'648',nameLower:'aurelio rodríguez'},
  {rank:505,name:'Virgil Davis',value:'647',nameLower:'virgil davis'},
  {rank:506,name:'Bert Campaneris',value:'646',nameLower:'bert campaneris'},
  {rank:507,name:'Tim McCarver',value:'645',nameLower:'tim mccarver'},
  {rank:508,name:'Max Muncy',value:'644',nameLower:'max muncy'},
  {rank:508,name:'Jack Rowe',value:'644',nameLower:'jack rowe'},
  {rank:509,name:'Don Mincher',value:'643',nameLower:'don mincher'},
  {rank:509,name:'John Morrill',value:'643',nameLower:'john morrill'},
  {rank:510,name:'Stan Hack',value:'642',nameLower:'stan hack'},
  {rank:510,name:'Fred Luderus',value:'642',nameLower:'fred luderus'},
  {rank:511,name:'Ketel Marte',value:'641',nameLower:'ketel marte'},
  {rank:511,name:'Bill Robinson',value:'641',nameLower:'bill robinson'},
  {rank:512,name:'Todd Frazier',value:'640',nameLower:'todd frazier'},
  {rank:512,name:'Mark Grudzielanek',value:'640',nameLower:'mark grudzielanek'},
  {rank:512,name:'Eddie Miller',value:'640',nameLower:'eddie miller'},
  {rank:513,name:'Coco Crisp',value:'639',nameLower:'coco crisp'},
  {rank:513,name:'Pablo Sandoval',value:'639',nameLower:'pablo sandoval'},
  {rank:514,name:'Kitty Bransfield',value:'637',nameLower:'kitty bransfield'},
  {rank:515,name:'Eduardo Escobar',value:'636',nameLower:'eduardo escobar'},
  {rank:515,name:'Curt Flood',value:'636',nameLower:'curt flood'},
  {rank:515,name:'Norm Siebern',value:'636',nameLower:'norm siebern'},
  {rank:516,name:'Steve Kemp',value:'634',nameLower:'steve kemp'},
  {rank:517,name:'Earle Combs',value:'633',nameLower:'earle combs'},
  {rank:517,name:'Eric McNair',value:'633',nameLower:'eric mcnair'},
  {rank:518,name:'Josh Willingham',value:'632',nameLower:'josh willingham'},
  {rank:519,name:'Ozzie Albies',value:'631',nameLower:'ozzie albies'},
  {rank:519,name:'John Corkhill',value:'631',nameLower:'john corkhill'},
  {rank:519,name:'Fielder Jones',value:'631',nameLower:'fielder jones'},
  {rank:519,name:'Matt Lawton',value:'631',nameLower:'matt lawton'},
  {rank:520,name:'Jacque Jones',value:'630',nameLower:'jacque jones'},
  {rank:520,name:'Pete Runnels',value:'630',nameLower:'pete runnels'},
  {rank:521,name:'Mark Loretta',value:'629',nameLower:'mark loretta'},
  {rank:521,name:'Mark Trumbo',value:'629',nameLower:'mark trumbo'},
  {rank:522,name:'Frankie Hayes',value:'628',nameLower:'frankie hayes'},
  {rank:522,name:'Terry Kennedy',value:'628',nameLower:'terry kennedy'},
  {rank:523,name:'Brandon Belt',value:'627',nameLower:'brandon belt'},
  {rank:523,name:'Dave Orr',value:'627',nameLower:'dave orr'},
  {rank:523,name:'Bill Russell',value:'627',nameLower:'bill russell'},
  {rank:524,name:'Mike Bordick',value:'626',nameLower:'mike bordick'},
  {rank:524,name:'Vladimir Guerrero Jr.',value:'626',nameLower:'vladimir guerrero jr.'},
  {rank:525,name:'Charles Zimmer',value:'625',nameLower:'charles zimmer'},
  {rank:526,name:'José Cruz',value:'624',nameLower:'josé cruz'},
  {rank:526,name:'Jim Gilliam',value:'624',nameLower:'jim gilliam'},
  {rank:526,name:'Marty Marion',value:'624',nameLower:'marty marion'},
  {rank:526,name:'Jim Sundberg',value:'624',nameLower:'jim sundberg'},
  {rank:527,name:'Chick Stahl',value:'622',nameLower:'chick stahl'},
  {rank:528,name:'Dewey Creacy',value:'621',nameLower:'dewey creacy'},
  {rank:528,name:'Monte Cross',value:'621',nameLower:'monte cross'},
  {rank:528,name:'Bug Holliday',value:'621',nameLower:'bug holliday'},
  {rank:528,name:'Jimmie Wilson',value:'621',nameLower:'jimmie wilson'},
  {rank:529,name:'Paul Blair',value:'620',nameLower:'paul blair'},
  {rank:529,name:'Mel Hall',value:'620',nameLower:'mel hall'},
  {rank:529,name:'Howie Shanks',value:'620',nameLower:'howie shanks'},
  {rank:530,name:'Tommy Griffith',value:'619',nameLower:'tommy griffith'},
  {rank:530,name:'Ozzie Guillén',value:'619',nameLower:'ozzie guillén'},
  {rank:531,name:'Dom DiMaggio',value:'618',nameLower:'dom dimaggio'},
  {rank:531,name:'George Gore',value:'618',nameLower:'george gore'},
  {rank:531,name:'Candy Maldonado',value:'618',nameLower:'candy maldonado'},
  {rank:531,name:'Mitch Moreland',value:'618',nameLower:'mitch moreland'},
  {rank:531,name:'Kevin Youkilis',value:'618',nameLower:'kevin youkilis'},
  {rank:532,name:'Ginger Beaumont',value:'617',nameLower:'ginger beaumont'},
  {rank:532,name:'Clyde Milan',value:'617',nameLower:'clyde milan'},
  {rank:533,name:'Casey Blake',value:'616',nameLower:'casey blake'},
  {rank:533,name:'Elbie Fletcher',value:'616',nameLower:'elbie fletcher'},
  {rank:534,name:'Tony González',value:'615',nameLower:'tony gonzález'},
  {rank:534,name:'Chuck Knoblauch',value:'615',nameLower:'chuck knoblauch'},
  {rank:534,name:'Mark McLemore',value:'615',nameLower:'mark mclemore'},
  {rank:535,name:'Rusty Greer',value:'614',nameLower:'rusty greer'},
  {rank:535,name:'Charlie Hickman',value:'614',nameLower:'charlie hickman'},
  {rank:535,name:'Ed Kranepool',value:'614',nameLower:'ed kranepool'},
  {rank:535,name:'Davey Lopes',value:'614',nameLower:'davey lopes'},
  {rank:536,name:'Kevin Seitzer',value:'613',nameLower:'kevin seitzer'},
  {rank:537,name:'Kevin Bass',value:'611',nameLower:'kevin bass'},
  {rank:537,name:'George Burns',value:'611',nameLower:'george burns'},
  {rank:538,name:'Don Hurst',value:'610',nameLower:'don hurst'},
  {rank:538,name:'Mike Lieberthal',value:'610',nameLower:'mike lieberthal'},
  {rank:538,name:'Jim Northrup',value:'610',nameLower:'jim northrup'},
  {rank:538,name:'Billy Rogell',value:'610',nameLower:'billy rogell'},
  {rank:539,name:'Davey Johnson',value:'609',nameLower:'davey johnson'},
  {rank:539,name:'Bill Joyce',value:'609',nameLower:'bill joyce'},
  {rank:539,name:'Dwayne Murphy',value:'609',nameLower:'dwayne murphy'},
  {rank:539,name:'Martín Prado',value:'609',nameLower:'martín prado'},
  {rank:539,name:'Neil Walker',value:'609',nameLower:'neil walker'},
  {rank:540,name:'Gus Triandos',value:'608',nameLower:'gus triandos'},
  {rank:541,name:'Brad Ausmus',value:'607',nameLower:'brad ausmus'},
  {rank:541,name:'Matt Chapman',value:'607',nameLower:'matt chapman'},
  {rank:541,name:'Willson Contreras',value:'607',nameLower:'willson contreras'},
  {rank:541,name:'Buddy Lewis',value:'607',nameLower:'buddy lewis'},
  {rank:542,name:'Ken McMullen',value:'606',nameLower:'ken mcmullen'},
  {rank:542,name:'Denis Menke',value:'606',nameLower:'denis menke'},
  {rank:542,name:'Joc Pederson',value:'606',nameLower:'joc pederson'},
  {rank:542,name:'Kevin Young',value:'606',nameLower:'kevin young'},
  {rank:543,name:'C.J. Cron',value:'604',nameLower:'c.j. cron'},
  {rank:543,name:'Greg Gagne',value:'604',nameLower:'greg gagne'},
  {rank:543,name:'Willard Marshall',value:'604',nameLower:'willard marshall'},
  {rank:544,name:'Glenn Davis',value:'603',nameLower:'glenn davis'},
  {rank:544,name:'Wilmer Flores',value:'603',nameLower:'wilmer flores'},
  {rank:544,name:'José Hernández',value:'603',nameLower:'josé hernández'},
  {rank:545,name:'Ronnie Belliard',value:'601',nameLower:'ronnie belliard'},
  {rank:545,name:'Eddie Joost',value:'601',nameLower:'eddie joost'},
  {rank:545,name:'Elmer Valo',value:'601',nameLower:'elmer valo'},
  {rank:545,name:'George Wood',value:'601',nameLower:'george wood'},
  {rank:546,name:'Rob Deer',value:'600',nameLower:'rob deer'},
  {rank:547,name:'Roy Cullenbine',value:'599',nameLower:'roy cullenbine'},
  {rank:547,name:'Todd Hundley',value:'599',nameLower:'todd hundley'},
  {rank:547,name:'Moose Solters',value:'599',nameLower:'moose solters'},
  {rank:547,name:'Jim Spencer',value:'599',nameLower:'jim spencer'},
  {rank:548,name:'Pedro Feliz',value:'598',nameLower:'pedro feliz'},
  {rank:548,name:'Ian Happ',value:'598',nameLower:'ian happ'},
  {rank:548,name:'Jim Tabor',value:'598',nameLower:'jim tabor'},
  {rank:548,name:'Tony Taylor',value:'598',nameLower:'tony taylor'},
  {rank:548,name:'Lloyd Waner',value:'598',nameLower:'lloyd waner'},
  {rank:549,name:'Cool Papa Bell',value:'597',nameLower:'cool papa bell'},
  {rank:549,name:'Andrew Benintendi',value:'597',nameLower:'andrew benintendi'},
  {rank:549,name:'Gary Ward',value:'597',nameLower:'gary ward'},
  {rank:550,name:'Enos Cabell',value:'596',nameLower:'enos cabell'},
  {rank:550,name:'Frank Chance',value:'596',nameLower:'frank chance'},
  {rank:550,name:'Chase Headley',value:'596',nameLower:'chase headley'},
  {rank:551,name:'Ray Knight',value:'595',nameLower:'ray knight'},
  {rank:552,name:'Jed Lowrie',value:'594',nameLower:'jed lowrie'},
  {rank:552,name:'Roy McMillan',value:'594',nameLower:'roy mcmillan'},
  {rank:552,name:'Johnny Ray',value:'594',nameLower:'johnny ray'},
  {rank:552,name:'Ty Wigginton',value:'594',nameLower:'ty wigginton'},
  {rank:552,name:'Walt Wilmot',value:'594',nameLower:'walt wilmot'},
  {rank:553,name:'Willy Adames',value:'593',nameLower:'willy adames'},
  {rank:553,name:'Dick Hoblitzell',value:'593',nameLower:'dick hoblitzell'},
  {rank:553,name:'Cookie Rojas',value:'593',nameLower:'cookie rojas'},
  {rank:553,name:'Ray Schalk',value:'593',nameLower:'ray schalk'},
  {rank:553,name:'Fred Schulte',value:'593',nameLower:'fred schulte'},
  {rank:554,name:'Yasmani Grandal',value:'592',nameLower:'yasmani grandal'},
  {rank:554,name:'John Kruk',value:'592',nameLower:'john kruk'},
  {rank:554,name:'Chicken Wolf',value:'592',nameLower:'chicken wolf'},
  {rank:554,name:'Ross Youngs',value:'592',nameLower:'ross youngs'},
  {rank:555,name:'Dave Bancroft',value:'591',nameLower:'dave bancroft'},
  {rank:555,name:'Frank Demaree',value:'591',nameLower:'frank demaree'},
  {rank:555,name:'Billy Goodman',value:'591',nameLower:'billy goodman'},
  {rank:555,name:'Sixto Lezcano',value:'591',nameLower:'sixto lezcano'},
  {rank:555,name:'Héctor López',value:'591',nameLower:'héctor lópez'},
  {rank:555,name:'Bill Melton',value:'591',nameLower:'bill melton'},
  {rank:555,name:'Troy O\'Leary',value:'591',nameLower:'troy o\'leary'},
  {rank:555,name:'Jim Piersall',value:'591',nameLower:'jim piersall'},
  {rank:556,name:'Khris Davis',value:'590',nameLower:'khris davis'},
  {rank:556,name:'Alexei Ramírez',value:'590',nameLower:'alexei ramírez'},
  {rank:556,name:'Chris Young',value:'590',nameLower:'chris young'},
  {rank:557,name:'David Bell',value:'589',nameLower:'david bell'},
  {rank:557,name:'Christian Walker',value:'589',nameLower:'christian walker'},
  {rank:558,name:'Sandy Alomar',value:'588',nameLower:'sandy alomar'},
  {rank:558,name:'Darren Daulton',value:'588',nameLower:'darren daulton'},
  {rank:558,name:'Jorge Soler',value:'588',nameLower:'jorge soler'},
  {rank:559,name:'Rafael Furcal',value:'587',nameLower:'rafael furcal'},
  {rank:559,name:'Ryan Ludwick',value:'587',nameLower:'ryan ludwick'},
  {rank:560,name:'Richie Ashburn',value:'586',nameLower:'richie ashburn'},
  {rank:560,name:'Rube Bressler',value:'586',nameLower:'rube bressler'},
  {rank:560,name:'Glenallen Hill',value:'586',nameLower:'glenallen hill'},
  {rank:560,name:'Biz Mackey',value:'586',nameLower:'biz mackey'},
  {rank:560,name:'B.J. Upton',value:'586',nameLower:'b.j. upton'},
  {rank:561,name:'Roberto Kelly',value:'585',nameLower:'roberto kelly'},
  {rank:561,name:'Orlando Merced',value:'585',nameLower:'orlando merced'},
  {rank:561,name:'Manny Sanguillén',value:'585',nameLower:'manny sanguillén'},
  {rank:561,name:'Jack Tobin',value:'585',nameLower:'jack tobin'},
  {rank:561,name:'Willie Wilson',value:'585',nameLower:'willie wilson'},
  {rank:562,name:'Vince DiMaggio',value:'584',nameLower:'vince dimaggio'},
  {rank:563,name:'Darrin Fletcher',value:'583',nameLower:'darrin fletcher'},
  {rank:563,name:'Eddie Rosario',value:'583',nameLower:'eddie rosario'},
  {rank:564,name:'Kole Calhoun',value:'582',nameLower:'kole calhoun'},
  {rank:564,name:'Bob Fothergill',value:'582',nameLower:'bob fothergill'},
  {rank:565,name:'Tommy Holmes',value:'581',nameLower:'tommy holmes'},
  {rank:566,name:'Dave Martinez',value:'580',nameLower:'dave martinez'},
  {rank:566,name:'Shannon Stewart',value:'580',nameLower:'shannon stewart'},
  {rank:567,name:'Ruppert Jones',value:'579',nameLower:'ruppert jones'},
  {rank:567,name:'Bill Lange',value:'579',nameLower:'bill lange'},
  {rank:568,name:'Brett Butler',value:'578',nameLower:'brett butler'},
  {rank:568,name:'Brett Gardner',value:'578',nameLower:'brett gardner'},
  {rank:568,name:'Jim Ray Hart',value:'578',nameLower:'jim ray hart'},
  {rank:569,name:'Michael Conforto',value:'577',nameLower:'michael conforto'},
  {rank:569,name:'Dode Paskert',value:'577',nameLower:'dode paskert'},
  {rank:570,name:'Ken Henderson',value:'576',nameLower:'ken henderson'},
  {rank:570,name:'Gil McDougald',value:'576',nameLower:'gil mcdougald'},
  {rank:570,name:'George Selkirk',value:'576',nameLower:'george selkirk'},
  {rank:571,name:'Jerry Mumphrey',value:'575',nameLower:'jerry mumphrey'},
  {rank:571,name:'Red Murray',value:'575',nameLower:'red murray'},
  {rank:571,name:'Josh Reddick',value:'575',nameLower:'josh reddick'},
  {rank:571,name:'Stan Spence',value:'575',nameLower:'stan spence'},
  {rank:572,name:'Tom Herr',value:'574',nameLower:'tom herr'},
  {rank:573,name:'David DeJesus',value:'573',nameLower:'david dejesus'},
  {rank:573,name:'Odell Hale',value:'573',nameLower:'odell hale'},
  {rank:574,name:'Buck Leonard',value:'572',nameLower:'buck leonard'},
  {rank:574,name:'Jorge Polanco',value:'572',nameLower:'jorge polanco'},
  {rank:575,name:'Adam Kennedy',value:'571',nameLower:'adam kennedy'},
  {rank:575,name:'Manny Trillo',value:'571',nameLower:'manny trillo'},
  {rank:576,name:'Jack Boyle',value:'570',nameLower:'jack boyle'},
  {rank:576,name:'Ferris Fain',value:'570',nameLower:'ferris fain'},
  {rank:576,name:'Charles Johnson',value:'570',nameLower:'charles johnson'},
  {rank:576,name:'Jerry Morales',value:'570',nameLower:'jerry morales'},
  {rank:576,name:'Justin Smoak',value:'570',nameLower:'justin smoak'},
  {rank:576,name:'Owen Wilson',value:'570',nameLower:'owen wilson'},
  {rank:577,name:'Babe Dahlgren',value:'569',nameLower:'babe dahlgren'},
  {rank:577,name:'David Peralta',value:'569',nameLower:'david peralta'},
  {rank:578,name:'Jim Gantner',value:'568',nameLower:'jim gantner'},
  {rank:578,name:'Rougned Odor',value:'568',nameLower:'rougned odor'},
  {rank:578,name:'Hank Thompson',value:'568',nameLower:'hank thompson'},
  {rank:579,name:'Joe Dugan',value:'567',nameLower:'joe dugan'},
  {rank:579,name:'Leo Durocher',value:'567',nameLower:'leo durocher'},
  {rank:579,name:'Tommy Harper',value:'567',nameLower:'tommy harper'},
  {rank:579,name:'George Miller',value:'567',nameLower:'george miller'},
  {rank:580,name:'Wil Cordero',value:'566',nameLower:'wil cordero'},
  {rank:580,name:'Adam Duvall',value:'566',nameLower:'adam duvall'},
  {rank:580,name:'Dan Ford',value:'566',nameLower:'dan ford'},
  {rank:580,name:'Heinie Groh',value:'566',nameLower:'heinie groh'},
  {rank:580,name:'Delmon Young',value:'566',nameLower:'delmon young'},
];

// Registry of all static datasets — add new ones here as they're imported
const STATIC_DATASETS = {
  BBREF_RBI_ALL_TIME: BBREF_RBI_ALL_TIME,
};

// Fetch from a static BR dataset instead of the MLB API
function fetchStaticPlayers(dataset){
  return dataset.map(p => ({...p}));
}

const MLB = 'https://statsapi.mlb.com/api/v1';

// Assigns dense ranks: ties share a rank, next distinct value increments by 1 (not skipped)
// e.g. raw values [10, 9, 9, 8] -> ranks [1, 2, 2, 3]
function assignDenseRanks(items, rawKey){
  let rank = 0;
  let lastVal = null;
  return items.map((item) => {
    const val = item[rawKey];
    if(lastVal === null || val !== lastVal){
      rank++;
      lastVal = val;
    }
    return { ...item, rank };
  });
}

async function fetchOneSeason(group, statDef, season, pool, position){
  const order = statDef.order||'desc';
  const playerPool = statDef.pool||pool||'ALL';
  const params = new URLSearchParams({
    stats: statDef.type, group, gameType:'R',
    season, playerPool, limit:300,
    sortStat:statDef.key, order
  });
  if(position && position !== 'ALL') params.set('position', position);
  const r = await fetch(`${MLB}/stats?${params}`);
  if(!r.ok) throw new Error(`MLB API error ${r.status}`);
  const d = await r.json();
  return d.stats?.[0]?.splits || [];
}

async function fetchPlayers(group, statDef, season, pool, position){
  const isCareer = season==='career';
  const order = statDef.order||'desc';

  // Handle static Baseball Reference datasets — ignore season entirely
  if(statDef.type === 'static'){
    const dataset = STATIC_DATASETS[statDef.dataset];
    if(!dataset) throw new Error('Static dataset not found: ' + statDef.dataset);
    return fetchStaticPlayers(dataset);
  }

  let years = [];
  if(isCareer){
    // career endpoint
  } else if(String(season).startsWith('range:')){
    const [,range] = season.split(':');
    const [start, end] = range.split('-').map(Number);
    for(let y=start; y<=end; y++) years.push(y);
  } else if(String(season).startsWith('decade:')){
    const start = Number(season.split(':')[1]);
    const end = start === 2020 ? 2025 : start + 9;
    for(let y=start; y<=end; y++) years.push(y);
  } else {
    years = [season];
  }

  if(isCareer){
    const playerPool = 'ALL';
    const statType = statDef.type === 'sabermetrics' ? 'sabermetrics' : 'career';
    const params = new URLSearchParams({
      stats: statType, group, gameType:'R',
      playerPool, limit:300,
      sortStat:statDef.key, order:'desc'
    });
    if(position && position !== 'ALL') params.set('position', position);
    const r = await fetch(`${MLB}/stats?${params}`);
    if(!r.ok) throw new Error(`MLB API error ${r.status}`);
    const d = await r.json();
    const splits = d.stats?.[0]?.splits || [];
    if(!splits.length) throw new Error('No data returned. Try a different season or category.');
    const mapped = splits.map((s)=>({
      rawVal: parseFloat(s.stat[statDef.key]),
      name:s.player?.fullName||'?',
      team:s.team?.name||'',
      value:String(statDef.fmt(s.stat[statDef.key])),
      nameLower:(s.player?.fullName||'').toLowerCase()
    }));
    return assignDenseRanks(mapped, 'rawVal');
  }

  if(years.length === 1){
    const playerPool = statDef.pool||pool||'ALL';
    const params = new URLSearchParams({
      stats: statDef.type, group, gameType:'R',
      season: years[0], playerPool, limit:300,
      sortStat:statDef.key, order
    });
    if(position && position !== 'ALL') params.set('position', position);
    const r = await fetch(`${MLB}/stats?${params}`);
    if(!r.ok) throw new Error(`MLB API error ${r.status}`);
    const d = await r.json();
    const splits = d.stats?.[0]?.splits || [];
    if(!splits.length) throw new Error('No data returned. Try a different season or category.');
    const mapped = splits.map((s)=>({
      rawVal: parseFloat(s.stat[statDef.key]),
      name:s.player?.fullName||'?',
      team:s.team?.name||'',
      value:String(statDef.fmt(s.stat[statDef.key])),
      nameLower:(s.player?.fullName||'').toLowerCase()
    }));
    return assignDenseRanks(mapped, 'rawVal');
  }

  const allSplits = await Promise.all(
    years.map(y => fetchOneSeason(group, statDef, y, pool, position).catch(()=>[]))
  );

  const totals = {};
  for(const seasonSplits of allSplits){
    for(const s of seasonSplits){
      const id = s.player?.id;
      if(!id) continue;
      const raw = parseFloat(s.stat[statDef.key]);
      if(isNaN(raw)) continue;
      if(!totals[id]){
        totals[id] = {name: s.player?.fullName||'?', team: s.team?.name||'—', total: 0};
      }
      totals[id].total += raw;
    }
  }

  if(!Object.keys(totals).length) throw new Error('No data returned for this range.');

  const isAsc = order === 'asc';
  const sorted = Object.values(totals).sort((a,b) => isAsc ? a.total-b.total : b.total-a.total);
  const top300 = sorted.slice(0, 300);

  const mapped = top300.map((p)=>({
    rawVal: p.total,
    name:p.name,
    team:p.team,
    value:String(statDef.fmt(p.total)),
    nameLower:p.name.toLowerCase()
  }));
  return assignDenseRanks(mapped, 'rawVal');
}
